-- Generated by scripts/gen-schema.sh from migrations/. Do not edit.
-- Regenerate with: scripts/gen-schema.sh

--
-- PostgreSQL database dump
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: tier1; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA tier1;


--
-- Name: SCHEMA tier1; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA tier1 IS 'Tier 1 - derived and disposable. Chronicle''s account of what exists, and what it derives from its own corpus: proposals, entities, indexes. Regenerable from a source of truth outside these tables. Never hand-edited.';


--
-- Name: tier2; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA tier2;


--
-- Name: SCHEMA tier2; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA tier2 IS 'Tier 2 - authored and irreplaceable. What a person said or wrote: memos, transcripts, notes, discussions, plans. Not derivable from anything, cannot be rebuilt. Nothing on a tier-1 write path may reach these tables.';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version text NOT NULL,
    applied_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: user_tokens; Type: TABLE; Schema: tier2; Owner: -
--

CREATE TABLE tier2.user_tokens (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    kind text NOT NULL,
    token_hash text NOT NULL,
    label text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_used_at timestamp with time zone,
    used_at timestamp with time zone,
    expires_at timestamp with time zone,
    CONSTRAINT user_tokens_kind_check CHECK ((kind = ANY (ARRAY['invite'::text, 'session'::text])))
);


--
-- Name: users; Type: TABLE; Schema: tier2; Owner: -
--

CREATE TABLE tier2.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email text NOT NULL,
    display_name text NOT NULL,
    kind text DEFAULT 'person'::text NOT NULL,
    is_owner boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT users_kind_check CHECK ((kind = ANY (ARRAY['person'::text, 'agent'::text]))),
    CONSTRAINT users_owner_is_a_person CHECK (((NOT is_owner) OR (kind = 'person'::text)))
);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: user_tokens user_tokens_pkey; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.user_tokens
    ADD CONSTRAINT user_tokens_pkey PRIMARY KEY (id);


--
-- Name: user_tokens user_tokens_token_hash_key; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.user_tokens
    ADD CONSTRAINT user_tokens_token_hash_key UNIQUE (token_hash);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: user_tokens_user_id; Type: INDEX; Schema: tier2; Owner: -
--

CREATE INDEX user_tokens_user_id ON tier2.user_tokens USING btree (user_id);


--
-- Name: users_single_owner; Type: INDEX; Schema: tier2; Owner: -
--

CREATE UNIQUE INDEX users_single_owner ON tier2.users USING btree (is_owner) WHERE is_owner;


--
-- Name: user_tokens user_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.user_tokens
    ADD CONSTRAINT user_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES tier2.users(id) ON DELETE CASCADE;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: -
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- Name: SCHEMA tier1; Type: ACL; Schema: -; Owner: -
--

GRANT ALL ON SCHEMA tier1 TO chronicle_tier1;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: tier1; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA tier1 GRANT SELECT,USAGE ON SEQUENCES TO chronicle_tier1;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: tier1; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA tier1 GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO chronicle_tier1;


--
-- PostgreSQL database dump complete
--


