-- Generated by scripts/gen-schema.sh from migrations/. Do not edit.
-- Regenerate with: scripts/gen-schema.sh

--
-- PostgreSQL database dump
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: tier1; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA tier1;


--
-- Name: SCHEMA tier1; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA tier1 IS 'Tier 1 - derived and disposable. Chronicle''s account of what exists, and what it derives from its own corpus: proposals, entities, indexes. Regenerable from a source of truth outside these tables. Never hand-edited.';


--
-- Name: tier2; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA tier2;


--
-- Name: SCHEMA tier2; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA tier2 IS 'Tier 2 - authored and irreplaceable. What a person said or wrote: memos, transcripts, notes, discussions, plans. Not derivable from anything, cannot be rebuilt. Nothing on a tier-1 write path may reach these tables.';


--
-- Name: memo_proposals_guard(); Type: FUNCTION; Schema: tier1; Owner: -
--

CREATE FUNCTION tier1.memo_proposals_guard() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        -- On tier2.transcripts' pattern, which refuses to re-attribute a row
        -- to another memo or model. Same reason: the identity is what makes
        -- the row mean anything, and a re-attributed proposal is a proposal
        -- credited to a model that never said it.
        IF NEW.memo_id  IS DISTINCT FROM OLD.memo_id
        OR NEW.proposer IS DISTINCT FROM OLD.proposer THEN
            RAISE EXCEPTION 'a proposal may not be re-attributed to another memo or proposer'
                USING ERRCODE = 'CH010';
        END IF;

        -- MONOTONE, like CHRN-22's audio_pruned_at. A generation that can go
        -- backwards is a generation an accept can be replayed against, which
        -- is the drift this column exists to close.
        IF NEW.generation < OLD.generation THEN
            RAISE EXCEPTION 'proposal generation may not decrease (% -> %)',
                OLD.generation, NEW.generation
                USING ERRCODE = 'CH011';
        END IF;

        NEW.updated_at := now();
    END IF;
    RETURN NEW;
END
$$;


--
-- Name: memo_links_guard(); Type: FUNCTION; Schema: tier2; Owner: -
--

CREATE FUNCTION tier2.memo_links_guard() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    -- On tier1.memo_proposals' pattern and tier2.transcripts' before it: the
    -- identity is what makes the row mean anything, and a re-attributed
    -- decision is a decision credited to a memo nobody made it about.
    IF NEW.memo_id IS DISTINCT FROM OLD.memo_id THEN
        RAISE EXCEPTION 'a memo link may not be re-attributed to another memo'
            USING ERRCODE = 'CH020';
    END IF;

    -- CONFIRMED IS TERMINAL, and this is load-bearing rather than tidy.
    --
    -- The accept path answers `applied` with the stored key for a memo that is
    -- already triaged, and it does that WITHOUT an outward call. That answer is
    -- only honest while a confirmation cannot be withdrawn — if a later sweep
    -- or a later batch could un-confirm a row, the key an operator was told
    -- about could stop being the ticket their memo became, and nothing would
    -- have logged the change.
    IF OLD.confirmed_at IS NOT NULL
       AND (NEW.confirmed_at IS DISTINCT FROM OLD.confirmed_at
            OR NEW.ticket_key IS DISTINCT FROM OLD.ticket_key
            OR NEW.destination IS DISTINCT FROM OLD.destination) THEN
        RAISE EXCEPTION 'a confirmed memo link is immutable (memo %)', OLD.memo_id
            USING ERRCODE = 'CH021';
    END IF;

    -- RE-ARMING A REFUSED ROW MUST BE A WHOLE NEW DECISION.
    --
    -- A refusal is an outcome, and the row keeps it so the operator can be told
    -- why. Clearing `refused_at` is how a corrected decision reclaims the row —
    -- but a corrected decision that re-sent the SAME idempotency key would
    -- replay the cached refusal it was correcting, which is the twenty-four
    -- hour trap `sent_idempotency_key` exists to close. Re-arming without a
    -- fresh key is therefore refused here, where it cannot be forgotten,
    -- rather than left to the one code path that does it today.
    IF OLD.refused_at IS NOT NULL AND NEW.refused_at IS NULL
       AND NEW.sent_idempotency_key = OLD.sent_idempotency_key THEN
        RAISE EXCEPTION 're-arming a refused memo link needs a fresh idempotency key (memo %)', OLD.memo_id
            USING ERRCODE = 'CH022';
    END IF;

    NEW.updated_at := now();
    RETURN NEW;
END
$$;


--
-- Name: memos_guard(); Type: FUNCTION; Schema: tier2; Owner: -
--

CREATE FUNCTION tier2.memos_guard() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    -- One entry point. A memo exists only once its audio is complete and
    -- durable, so there is no state meaning "maybe there are bytes".
    IF TG_OP = 'INSERT' THEN
        IF NEW.state <> 'captured' THEN
            RAISE EXCEPTION 'memo must be created in state captured, got %', NEW.state
                USING ERRCODE = 'CH003';
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.author_id    IS DISTINCT FROM OLD.author_id
    OR NEW.content_hash IS DISTINCT FROM OLD.content_hash
    OR NEW.byte_size    IS DISTINCT FROM OLD.byte_size
    OR NEW.captured_at  IS DISTINCT FROM OLD.captured_at THEN
        RAISE EXCEPTION 'memo identity and captured_at are immutable'
            USING ERRCODE = 'CH002';
    END IF;

    -- 'discarded' appears only as a target and never as a source: that is how
    -- terminal is written down, where it can be read. 'held' keeps an exit to
    -- 'queued' even after its audio prunes, which is why a worker claiming a
    -- memo that already has a durable transcript must skip ASR (E3) rather
    -- than reach for bytes that are gone.
    IF NEW.state IS DISTINCT FROM OLD.state
       AND (OLD.state || '>' || NEW.state) <> ALL (ARRAY[
             'captured>queued',          'captured>held',      'captured>discarded',
             'queued>transcribing',      'queued>held',        'queued>discarded',
             'transcribing>transcribed', 'transcribing>queued',
             'transcribing>held',        'transcribing>discarded',
             'transcribed>triaged',      'transcribed>held',   'transcribed>discarded',
             'triaged>held',             'triaged>discarded',
             'held>queued',              'held>discarded'
       ]) THEN
        RAISE EXCEPTION 'illegal memo state transition % -> %', OLD.state, NEW.state
            USING ERRCODE = 'CH001';
    END IF;

    NEW.updated_at := now();
    RETURN NEW;
END
$$;


--
-- Name: note_deletions_guard(); Type: FUNCTION; Schema: tier2; Owner: -
--

CREATE FUNCTION tier2.note_deletions_guard() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'a deletion record is not removable'
            USING ERRCODE = 'CH070';
    END IF;

    IF TG_OP = 'UPDATE' THEN
        -- The only legal UPDATE is closing an open record out.
        IF NEW.id         IS DISTINCT FROM OLD.id
        OR NEW.note_id    IS DISTINCT FROM OLD.note_id
        OR NEW.deleted_at IS DISTINCT FROM OLD.deleted_at
        OR NEW.deleted_by IS DISTINCT FROM OLD.deleted_by THEN
            RAISE EXCEPTION 'a deletion record is immutable except for being closed out'
                USING ERRCODE = 'CH070';
        END IF;
        IF OLD.undeleted_at IS NOT NULL THEN
            RAISE EXCEPTION 'that deletion record is already closed'
                USING ERRCODE = 'CH070';
        END IF;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM tier2.users
                    WHERE id = NEW.deleted_by AND kind = 'person') THEN
        RAISE EXCEPTION 'a note is deleted by a person, not by an agent'
            USING ERRCODE = 'CH041';
    END IF;
    IF NEW.undeleted_by IS NOT NULL
    AND NOT EXISTS (SELECT 1 FROM tier2.users
                     WHERE id = NEW.undeleted_by AND kind = 'person') THEN
        RAISE EXCEPTION 'a note is undeleted by a person, not by an agent'
            USING ERRCODE = 'CH041';
    END IF;
    RETURN NEW;
END
$$;


--
-- Name: note_revisions_guard(); Type: FUNCTION; Schema: tier2; Owner: -
--

CREATE FUNCTION tier2.note_revisions_guard() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN
        RAISE EXCEPTION 'a note revision is append-only: % is refused', TG_OP
            USING ERRCODE = 'CH040';
    END IF;

    -- INSERT.
    IF NEW.confirmed_by IS NULL THEN
        RAISE EXCEPTION 'a note revision needs a confirming person: nothing lands in authored text unattended'
            USING ERRCODE = 'CH041';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM tier2.users
                    WHERE id = NEW.confirmed_by AND kind = 'person') THEN
        RAISE EXCEPTION 'a note revision is confirmed by a person, not by an agent'
            USING ERRCODE = 'CH041';
    END IF;
    RETURN NEW;
END
$$;


--
-- Name: note_tags_guard(); Type: FUNCTION; Schema: tier2; Owner: -
--

CREATE FUNCTION tier2.note_tags_guard() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM tier2.notes
                WHERE id = NEW.note_id AND deleted_at IS NOT NULL) THEN
        RAISE EXCEPTION 'that note is deleted: undelete it before tagging it'
            USING ERRCODE = 'CH060';
    END IF;
    RETURN NEW;
END
$$;


--
-- Name: notes_guard(); Type: FUNCTION; Schema: tier2; Owner: -
--

CREATE FUNCTION tier2.notes_guard() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    changed  TEXT;
    old_seq  INTEGER;
    new_seq  INTEGER;
BEGIN
    IF TG_OP = 'UPDATE' THEN
        -- Identity first, and kept byte-identical to 0011. It is a subset of
        -- the enumeration below, and it stays because it names the rule a
        -- caller has actually broken instead of listing a column.
        IF NEW.id        IS DISTINCT FROM OLD.id
        OR NEW.number    IS DISTINCT FROM OLD.number
        OR NEW.author_id IS DISTINCT FROM OLD.author_id THEN
            RAISE EXCEPTION 'note identity is immutable (id, number, author)'
                USING ERRCODE = 'CH030';
        END IF;

        -- THE ALLOW LIST. page_id is a move, current_revision_id is an edit,
        -- deleted_at/deleted_by are a soft delete, updated_at is maintained
        -- below. Everything else — including every column added after this
        -- migration — is refused.
        SELECT string_agg(n.key, ', ' ORDER BY n.key) INTO changed
          FROM jsonb_each(to_jsonb(NEW)) n
          JOIN jsonb_each(to_jsonb(OLD)) o ON o.key = n.key
         WHERE n.value IS DISTINCT FROM o.value
           AND n.key <> ALL (ARRAY['page_id', 'current_revision_id',
                                   'deleted_at', 'deleted_by', 'updated_at']);
        IF changed IS NOT NULL THEN
            RAISE EXCEPTION
                'tier2.notes permits updating page_id, current_revision_id, deleted_at, deleted_by only; refused: %',
                changed
                USING ERRCODE = 'CH031';
        END IF;

        -- A DELETED NOTE IS NOT EDITABLE. Undelete first — which is itself
        -- recorded, in tier2.note_deletions. Without this an agent holding a
        -- CHRN-67 write scope can go on editing a note nobody can see, and
        -- every read surface filters it out so nobody would.
        --
        -- Note this permits the undelete itself: that UPDATE touches only
        -- deleted_at and deleted_by, neither of which is tested here.
        IF OLD.deleted_at IS NOT NULL
        AND (NEW.current_revision_id IS DISTINCT FROM OLD.current_revision_id
          OR NEW.page_id             IS DISTINCT FROM OLD.page_id) THEN
            RAISE EXCEPTION 'note % is deleted: undelete it before writing to it', OLD.number
                USING ERRCODE = 'CH033';
        END IF;

        -- FORWARD ONLY (ruling 1). A restore APPENDS a new revision carrying
        -- the old text, so current_revision_id never needs to move backwards,
        -- and refusing it here makes a silent rewind unrepresentable rather
        -- than merely un-coded. This is what stops a CHRN-67 writer moving the
        -- pointer back and leaving no trace that anything happened.
        --
        -- BOTH LOOKUPS ARE SCOPED TO THIS NOTE, and that is load-bearing
        -- rather than tidy. A pointer at ANOTHER note's revision is not a
        -- rewind, it is nonsense, and 0011's composite notes_current_revision
        -- is what refuses it — with 23503, which CHRN-38's criterion 3 asserts
        -- on. Unscoped, this would find that revision's seq, compare it, and
        -- raise CH032 first, so a cross-note pointer would report itself as a
        -- failed restore. Scoped, new_seq comes back NULL and the guard steps
        -- aside for the foreign key that owns the question.
        IF NEW.current_revision_id IS DISTINCT FROM OLD.current_revision_id THEN
            SELECT seq INTO old_seq FROM tier2.note_revisions
             WHERE id = OLD.current_revision_id AND note_id = OLD.id;
            SELECT seq INTO new_seq FROM tier2.note_revisions
             WHERE id = NEW.current_revision_id AND note_id = OLD.id;
            IF new_seq IS NOT NULL AND old_seq IS NOT NULL AND new_seq <= old_seq THEN
                RAISE EXCEPTION
                    'note % cannot move from revision % back to %: restore by appending',
                    OLD.number, old_seq, new_seq
                    USING ERRCODE = 'CH032';
            END IF;
        END IF;

        -- A PERSON DELETES, AND A PERSON UNDELETES (ruling 4). Same rule and
        -- same code as the confirmer on a revision, because it is the same
        -- rule: no agent removes authored text from view unattended.
        IF NEW.deleted_by IS DISTINCT FROM OLD.deleted_by AND NEW.deleted_by IS NOT NULL THEN
            IF NOT EXISTS (SELECT 1 FROM tier2.users
                            WHERE id = NEW.deleted_by AND kind = 'person') THEN
                RAISE EXCEPTION 'a note is deleted by a person, not by an agent'
                    USING ERRCODE = 'CH041';
            END IF;
        END IF;

        -- As memos_guard, transcripts_guard and memo_links_guard all do.
        -- Without it, updated_at is a column nothing maintains.
        NEW.updated_at := now();
    END IF;
    RETURN NEW;
END
$$;


--
-- Name: pages_guard(); Type: FUNCTION; Schema: tier2; Owner: -
--

CREATE FUNCTION tier2.pages_guard() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    ancestor UUID;
    hops     INT := 0;
BEGIN
    IF TG_OP = 'UPDATE' THEN
        -- Identity is immutable. parent_id and slug deliberately are NOT:
        -- changing them is what a move and a rename ARE.
        IF NEW.id IS DISTINCT FROM OLD.id THEN
            RAISE EXCEPTION 'a page id is immutable'
                USING ERRCODE = 'CH051';
        END IF;
        NEW.updated_at := now();
    END IF;

    -- A CYCLE IS THE ONE STRUCTURAL ERROR THAT HIDES. A page made its own
    -- ancestor is still a perfectly valid row, its children still resolve to
    -- it, and every query that walks UP from a leaf runs forever while every
    -- query that walks DOWN from a root simply never reaches it. The subtree
    -- and all the notes in it become unreachable and unnameable without a
    -- single constraint being violated, which is why this is a trigger and not
    -- a rule in Go.
    ancestor := NEW.parent_id;
    WHILE ancestor IS NOT NULL LOOP
        IF ancestor = NEW.id THEN
            RAISE EXCEPTION 'a page may not be its own ancestor (page %)', NEW.id
                USING ERRCODE = 'CH050';
        END IF;
        hops := hops + 1;
        IF hops > 64 THEN
            -- Unreachable while this trigger has always been armed, and it is
            -- here so that a pre-existing cycle raises instead of hanging the
            -- connection that found it.
            RAISE EXCEPTION 'page ancestry exceeds 64 levels, which means a cycle'
                USING ERRCODE = 'CH050';
        END IF;
        SELECT parent_id INTO ancestor FROM tier2.pages WHERE id = ancestor;
    END LOOP;

    RETURN NEW;
END
$$;


--
-- Name: retention_rank(text); Type: FUNCTION; Schema: tier2; Owner: -
--

CREATE FUNCTION tier2.retention_rank(r text) RETURNS integer
    LANGUAGE sql IMMUTABLE STRICT
    AS $$
    SELECT CASE r WHEN 'discard_now' THEN 0
                  WHEN 'days_30'     THEN 1
                  WHEN 'forever'     THEN 2 END
$$;


--
-- Name: transcripts_guard(); Type: FUNCTION; Schema: tier2; Owner: -
--

CREATE FUNCTION tier2.transcripts_guard() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        RETURN NEW;
    END IF;

    IF NEW.memo_id IS DISTINCT FROM OLD.memo_id
    OR NEW.model   IS DISTINCT FROM OLD.model THEN
        RAISE EXCEPTION 'a transcript may not be re-attributed to another memo or model'
            USING ERRCODE = 'CH004';
    END IF;

    IF OLD.partial = false AND NEW.partial = true THEN
        RAISE EXCEPTION 'a complete transcript may not be replaced by a partial one'
            USING ERRCODE = 'CH005';
    END IF;

    IF OLD.partial = false AND NEW.text IS DISTINCT FROM OLD.text THEN
        RAISE EXCEPTION 'a complete transcript is authored content and is not rewritten in place'
            USING ERRCODE = 'CH005';
    END IF;

    NEW.updated_at := now();
    RETURN NEW;
END
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version text NOT NULL,
    applied_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: memo_jobs; Type: TABLE; Schema: tier1; Owner: -
--

CREATE TABLE tier1.memo_jobs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    memo_id uuid NOT NULL,
    idempotency_key text NOT NULL,
    model text NOT NULL,
    audio_sha256 text NOT NULL,
    job_id uuid,
    submitted_at timestamp with time zone,
    collected_at timestamp with time zone,
    failure_code text,
    failure_message text,
    superseded_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT memo_jobs_audio_sha256_check CHECK ((audio_sha256 ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT memo_jobs_idempotency_key_check CHECK (((length(idempotency_key) >= 16) AND (length(idempotency_key) <= 200)))
);


--
-- Name: TABLE memo_jobs; Type: COMMENT; Schema: tier1; Owner: -
--

COMMENT ON TABLE tier1.memo_jobs IS 'CHRN-27. Which ASR job a memo was submitted to, under which idempotency key. Tier 1 — regenerable, because Chronicle still holds the audio: losing a row costs one repeated GPU run and nothing else. Holds no transcript and no reference into tier 2.';


--
-- Name: memo_proposals; Type: TABLE; Schema: tier1; Owner: -
--

CREATE TABLE tier1.memo_proposals (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    memo_id uuid NOT NULL,
    transcript_id uuid NOT NULL,
    proposer text NOT NULL,
    generation integer DEFAULT 1 NOT NULL,
    status text DEFAULT 'valid'::text NOT NULL,
    payload jsonb,
    superseded_payload jsonb,
    cleared_fields jsonb,
    error text,
    raw_output text,
    last_attempt_raw text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT memo_proposals_generation_check CHECK ((generation >= 1)),
    CONSTRAINT memo_proposals_proposer_check CHECK ((proposer ~ '^[^/@]+/[^/@]+@[^/@]+$'::text)),
    CONSTRAINT memo_proposals_status_check CHECK ((status = ANY (ARRAY['valid'::text, 'needs_input'::text, 'invalid'::text]))),
    CONSTRAINT proposals_invalid_iff_no_payload CHECK (((status = 'invalid'::text) = (payload IS NULL))),
    CONSTRAINT proposals_raw_output_pairs_with_payload CHECK (((payload IS NULL) = (raw_output IS NULL)))
);


--
-- Name: TABLE memo_proposals; Type: COMMENT; Schema: tier1; Owner: -
--

COMMENT ON TABLE tier1.memo_proposals IS 'Derived from tier2.transcripts by Scribe. Regenerable: delete and re-run. Never hand-edited.';


--
-- Name: memo_uploads; Type: TABLE; Schema: tier1; Owner: -
--

CREATE TABLE tier1.memo_uploads (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    author_id uuid NOT NULL,
    idempotency_key text NOT NULL,
    content_hash text NOT NULL,
    byte_size bigint NOT NULL,
    retention text,
    original_filename text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_activity_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT memo_uploads_byte_size_check CHECK ((byte_size > 0)),
    CONSTRAINT memo_uploads_content_hash_check CHECK ((content_hash ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT memo_uploads_idempotency_key_check CHECK (((length(idempotency_key) >= 16) AND (length(idempotency_key) <= 200))),
    CONSTRAINT memo_uploads_retention_check CHECK (((retention IS NULL) OR (retention = ANY (ARRAY['discard_now'::text, 'days_30'::text, 'forever'::text]))))
);


--
-- Name: TABLE memo_uploads; Type: COMMENT; Schema: tier1; Owner: -
--

COMMENT ON TABLE tier1.memo_uploads IS 'CHRN-20. Uploads in flight: what the client declared it is sending, so the bytes can be checked against it. Tier 1 — regenerable from the client, which still holds the recording until the memo is acknowledged. Holds no reference into tier 2.';


--
-- Name: note_links; Type: TABLE; Schema: tier1; Owner: -
--

CREATE TABLE tier1.note_links (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    from_note_id uuid NOT NULL,
    from_revision_id uuid NOT NULL,
    to_number bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT note_links_to_number_check CHECK ((to_number > 0))
);


--
-- Name: TABLE note_links; Type: COMMENT; Schema: tier1; Owner: -
--

COMMENT ON TABLE tier1.note_links IS 'Derived from the current revision of each note by CHRN-42. Regenerable: delete every row and rebuild. Never hand-edited.';


--
-- Name: triage_holds; Type: TABLE; Schema: tier1; Owner: -
--

CREATE TABLE tier1.triage_holds (
    memo_id uuid NOT NULL,
    held_by uuid NOT NULL,
    reason text,
    held_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE triage_holds; Type: COMMENT; Schema: tier1; Owner: -
--

COMMENT ON TABLE tier1.triage_holds IS 'A routing decision deferred. TIER 1 because it is the ABSENCE of a decision: delete every row and the memos simply reappear on the triage screen. The memo itself stays `transcribed` — tier2.memos `held` means transcription failed and is a different thing (CHRN-34).';


--
-- Name: watch_seen; Type: TABLE; Schema: tier1; Owner: -
--

CREATE TABLE tier1.watch_seen (
    path text NOT NULL,
    size_bytes bigint NOT NULL,
    mtime timestamp with time zone NOT NULL,
    content_hash text NOT NULL,
    first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT watch_seen_content_hash_check CHECK ((content_hash ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT watch_seen_size_bytes_check CHECK ((size_bytes > 0))
);


--
-- Name: TABLE watch_seen; Type: COMMENT; Schema: tier1; Owner: -
--

COMMENT ON TABLE tier1.watch_seen IS 'CHRN-19. What the Copyparty watcher has already read, so a rescan is not a re-delivery. Derived from the inbox and rebuilt by re-hashing it; holds no reference into tier 2.';


--
-- Name: memo_arrivals; Type: TABLE; Schema: tier2; Owner: -
--

CREATE TABLE tier2.memo_arrivals (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    memo_id uuid NOT NULL,
    author_id uuid NOT NULL,
    source text NOT NULL,
    idempotency_key text,
    source_ref text,
    arrived_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT memo_arrivals_has_handle CHECK (((idempotency_key IS NOT NULL) OR (source_ref IS NOT NULL))),
    CONSTRAINT memo_arrivals_idempotency_key_check CHECK (((idempotency_key IS NULL) OR ((length(idempotency_key) >= 16) AND (length(idempotency_key) <= 200)))),
    CONSTRAINT memo_arrivals_source_check CHECK ((source = ANY (ARRAY['copyparty'::text, 'upload'::text]))),
    CONSTRAINT memo_arrivals_watched_path CHECK (((source <> 'copyparty'::text) OR (source_ref IS NOT NULL)))
);


--
-- Name: memo_links; Type: TABLE; Schema: tier2; Owner: -
--

CREATE TABLE tier2.memo_links (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    memo_id uuid NOT NULL,
    destination text NOT NULL,
    sent_project_key text,
    sent_type text,
    sent_title text,
    sent_description text,
    sent_idempotency_key text NOT NULL,
    ticket_key text,
    confirmed_at timestamp with time zone,
    swept_at timestamp with time zone,
    candidate_keys text[],
    refused_at timestamp with time zone,
    refused_status integer,
    refused_reason text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT memo_links_confirmed_ticket_has_a_key CHECK (((confirmed_at IS NULL) OR (destination <> 'TICKET'::text) OR (ticket_key IS NOT NULL))),
    CONSTRAINT memo_links_confirmed_xor_refused CHECK (((confirmed_at IS NULL) OR (refused_at IS NULL))),
    CONSTRAINT memo_links_destination_check CHECK ((destination = ANY (ARRAY['NOTE'::text, 'TICKET'::text, 'DISCUSSION'::text, 'DISCARD'::text]))),
    CONSTRAINT memo_links_refusal_states_why CHECK (((refused_at IS NULL) = (refused_reason IS NULL))),
    CONSTRAINT memo_links_sent_idempotency_key_check CHECK ((sent_idempotency_key <> ''::text)),
    CONSTRAINT memo_links_ticket_key_only_on_ticket CHECK (((ticket_key IS NULL) OR (destination = 'TICKET'::text)))
);


--
-- Name: TABLE memo_links; Type: COMMENT; Schema: tier2; Owner: -
--

COMMENT ON TABLE tier2.memo_links IS 'What a PERSON decided a memo becomes. Authored, not derived: nothing regenerates it. UNIQUE (memo_id) is the lock that keeps one memo from becoming two tickets.';


--
-- Name: memos; Type: TABLE; Schema: tier2; Owner: -
--

CREATE TABLE tier2.memos (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    author_id uuid NOT NULL,
    content_hash text NOT NULL,
    byte_size bigint NOT NULL,
    captured_at timestamp with time zone DEFAULT now() NOT NULL,
    state text DEFAULT 'captured'::text NOT NULL,
    state_reason text,
    retention text DEFAULT 'days_30'::text NOT NULL,
    audio_pruned_at timestamp with time zone,
    duration_ms integer,
    codec text,
    sample_rate_hz integer,
    original_filename text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT memos_byte_size_check CHECK ((byte_size > 0)),
    CONSTRAINT memos_content_hash_check CHECK ((content_hash ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT memos_duration_ms_check CHECK (((duration_ms IS NULL) OR (duration_ms > 0))),
    CONSTRAINT memos_retention_check CHECK ((retention = ANY (ARRAY['discard_now'::text, 'days_30'::text, 'forever'::text]))),
    CONSTRAINT memos_state_check CHECK ((state = ANY (ARRAY['captured'::text, 'queued'::text, 'transcribing'::text, 'transcribed'::text, 'triaged'::text, 'held'::text, 'discarded'::text])))
);


--
-- Name: note_deletions; Type: TABLE; Schema: tier2; Owner: -
--

CREATE TABLE tier2.note_deletions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    note_id uuid NOT NULL,
    deleted_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_by uuid NOT NULL,
    undeleted_at timestamp with time zone,
    undeleted_by uuid,
    CONSTRAINT note_deletions_undeleted_pair CHECK (((undeleted_at IS NULL) = (undeleted_by IS NULL)))
);


--
-- Name: TABLE note_deletions; Type: COMMENT; Schema: tier2; Owner: -
--

COMMENT ON TABLE tier2.note_deletions IS 'CHRN-39, ruling 5. One row per deletion of a note, closed out on undelete. Tier 2 — a record of a person''s act on authored text, regenerable from nothing. tier2.notes.deleted_at is the current state; this is the history.';


--
-- Name: note_number_seq; Type: SEQUENCE; Schema: tier2; Owner: -
--

CREATE SEQUENCE tier2.note_number_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: note_revisions; Type: TABLE; Schema: tier2; Owner: -
--

CREATE TABLE tier2.note_revisions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    note_id uuid NOT NULL,
    seq integer NOT NULL,
    title text NOT NULL,
    body text NOT NULL,
    memo_id uuid,
    author_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    confirmed_by uuid,
    verb text,
    restored_from uuid,
    CONSTRAINT note_revisions_seq_check CHECK ((seq > 0)),
    CONSTRAINT note_revisions_verb CHECK (((verb IS NULL) OR (verb = ANY (ARRAY['create'::text, 'append'::text, 'supersede'::text, 'relate'::text])))),
    CONSTRAINT note_revisions_verb_seq CHECK (((verb IS NULL) OR ((seq = 1) = (verb = ANY (ARRAY['create'::text, 'relate'::text])))))
);


--
-- Name: COLUMN note_revisions.confirmed_by; Type: COMMENT; Schema: tier2; Owner: -
--

COMMENT ON COLUMN tier2.note_revisions.confirmed_by IS 'CHRN-39. Who agreed to this text landing — never an agent, enforced by CH041. Distinct from author_id, which is whose words these are and may legitimately be an agent. NULL only on rows written before 0014.';


--
-- Name: COLUMN note_revisions.verb; Type: COMMENT; Schema: tier2; Owner: -
--

COMMENT ON COLUMN tier2.note_revisions.verb IS 'CHRN-39. What a person confirmed about a Scribe proposal: create, append, supersede or relate. NULL means authored directly.';


--
-- Name: COLUMN note_revisions.restored_from; Type: COMMENT; Schema: tier2; Owner: -
--

COMMENT ON COLUMN tier2.note_revisions.restored_from IS 'CHRN-39. The revision this one was restored from. A restore APPENDS rather than rewinding (ruling 1), so this is what distinguishes a restore from an ordinary edit that happens to reproduce old text.';


--
-- Name: note_tags; Type: TABLE; Schema: tier2; Owner: -
--

CREATE TABLE tier2.note_tags (
    note_id uuid NOT NULL,
    tag text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT note_tags_tag_check CHECK ((tag ~ '^[a-z0-9]+(-[a-z0-9]+)*$'::text))
);


--
-- Name: notes; Type: TABLE; Schema: tier2; Owner: -
--

CREATE TABLE tier2.notes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    number bigint DEFAULT nextval('tier2.note_number_seq'::regclass) NOT NULL,
    page_id uuid NOT NULL,
    current_revision_id uuid NOT NULL,
    author_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    CONSTRAINT notes_deleted_pair CHECK (((deleted_at IS NULL) = (deleted_by IS NULL)))
);


--
-- Name: page_redirects; Type: TABLE; Schema: tier2; Owner: -
--

CREATE TABLE tier2.page_redirects (
    from_path text NOT NULL,
    page_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT page_redirects_from_path_check CHECK ((from_path <> ''::text))
);


--
-- Name: pages; Type: TABLE; Schema: tier2; Owner: -
--

CREATE TABLE tier2.pages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    parent_id uuid,
    slug text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT pages_slug_check CHECK ((slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'::text))
);


--
-- Name: transcripts; Type: TABLE; Schema: tier2; Owner: -
--

CREATE TABLE tier2.transcripts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    memo_id uuid NOT NULL,
    text text NOT NULL,
    segments jsonb DEFAULT '[]'::jsonb NOT NULL,
    partial boolean NOT NULL,
    model text NOT NULL,
    backend text NOT NULL,
    audio_duration_ms bigint,
    covered_ms bigint,
    transcribed_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE transcripts; Type: COMMENT; Schema: tier2; Owner: -
--

COMMENT ON TABLE tier2.transcripts IS 'CHRN-27. What a memo said. Tier 2 — it outlives the audio CHRN-22 prunes at thirty days, and nothing regenerates it once that audio is gone. `partial` is the gate that pruner reads: durable iff a run completed and partial is false. Empty text with a completed run IS durable.';


--
-- Name: user_tokens; Type: TABLE; Schema: tier2; Owner: -
--

CREATE TABLE tier2.user_tokens (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    kind text NOT NULL,
    token_hash text NOT NULL,
    label text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_used_at timestamp with time zone,
    used_at timestamp with time zone,
    expires_at timestamp with time zone,
    CONSTRAINT user_tokens_kind_check CHECK ((kind = ANY (ARRAY['invite'::text, 'session'::text])))
);


--
-- Name: users; Type: TABLE; Schema: tier2; Owner: -
--

CREATE TABLE tier2.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email text NOT NULL,
    display_name text NOT NULL,
    kind text DEFAULT 'person'::text NOT NULL,
    is_owner boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT users_kind_check CHECK ((kind = ANY (ARRAY['person'::text, 'agent'::text]))),
    CONSTRAINT users_owner_is_a_person CHECK (((NOT is_owner) OR (kind = 'person'::text)))
);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: memo_jobs memo_jobs_pkey; Type: CONSTRAINT; Schema: tier1; Owner: -
--

ALTER TABLE ONLY tier1.memo_jobs
    ADD CONSTRAINT memo_jobs_pkey PRIMARY KEY (id);


--
-- Name: memo_proposals memo_proposals_pkey; Type: CONSTRAINT; Schema: tier1; Owner: -
--

ALTER TABLE ONLY tier1.memo_proposals
    ADD CONSTRAINT memo_proposals_pkey PRIMARY KEY (id);


--
-- Name: memo_uploads memo_uploads_pkey; Type: CONSTRAINT; Schema: tier1; Owner: -
--

ALTER TABLE ONLY tier1.memo_uploads
    ADD CONSTRAINT memo_uploads_pkey PRIMARY KEY (id);


--
-- Name: note_links note_links_from_note_id_to_number_key; Type: CONSTRAINT; Schema: tier1; Owner: -
--

ALTER TABLE ONLY tier1.note_links
    ADD CONSTRAINT note_links_from_note_id_to_number_key UNIQUE (from_note_id, to_number);


--
-- Name: note_links note_links_pkey; Type: CONSTRAINT; Schema: tier1; Owner: -
--

ALTER TABLE ONLY tier1.note_links
    ADD CONSTRAINT note_links_pkey PRIMARY KEY (id);


--
-- Name: triage_holds triage_holds_pkey; Type: CONSTRAINT; Schema: tier1; Owner: -
--

ALTER TABLE ONLY tier1.triage_holds
    ADD CONSTRAINT triage_holds_pkey PRIMARY KEY (memo_id);


--
-- Name: watch_seen watch_seen_pkey; Type: CONSTRAINT; Schema: tier1; Owner: -
--

ALTER TABLE ONLY tier1.watch_seen
    ADD CONSTRAINT watch_seen_pkey PRIMARY KEY (path);


--
-- Name: memo_arrivals memo_arrivals_pkey; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.memo_arrivals
    ADD CONSTRAINT memo_arrivals_pkey PRIMARY KEY (id);


--
-- Name: memo_links memo_links_memo_id_key; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.memo_links
    ADD CONSTRAINT memo_links_memo_id_key UNIQUE (memo_id);


--
-- Name: memo_links memo_links_pkey; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.memo_links
    ADD CONSTRAINT memo_links_pkey PRIMARY KEY (id);


--
-- Name: memos memos_pkey; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.memos
    ADD CONSTRAINT memos_pkey PRIMARY KEY (id);


--
-- Name: note_deletions note_deletions_pkey; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.note_deletions
    ADD CONSTRAINT note_deletions_pkey PRIMARY KEY (id);


--
-- Name: note_revisions note_revisions_id_note_id_key; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.note_revisions
    ADD CONSTRAINT note_revisions_id_note_id_key UNIQUE (id, note_id);


--
-- Name: note_revisions note_revisions_note_id_seq_key; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.note_revisions
    ADD CONSTRAINT note_revisions_note_id_seq_key UNIQUE (note_id, seq);


--
-- Name: note_revisions note_revisions_pkey; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.note_revisions
    ADD CONSTRAINT note_revisions_pkey PRIMARY KEY (id);


--
-- Name: note_tags note_tags_pkey; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.note_tags
    ADD CONSTRAINT note_tags_pkey PRIMARY KEY (note_id, tag);


--
-- Name: notes notes_number_key; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.notes
    ADD CONSTRAINT notes_number_key UNIQUE (number);


--
-- Name: notes notes_pkey; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.notes
    ADD CONSTRAINT notes_pkey PRIMARY KEY (id);


--
-- Name: page_redirects page_redirects_pkey; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.page_redirects
    ADD CONSTRAINT page_redirects_pkey PRIMARY KEY (from_path);


--
-- Name: pages pages_pkey; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.pages
    ADD CONSTRAINT pages_pkey PRIMARY KEY (id);


--
-- Name: transcripts transcripts_pkey; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.transcripts
    ADD CONSTRAINT transcripts_pkey PRIMARY KEY (id);


--
-- Name: user_tokens user_tokens_pkey; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.user_tokens
    ADD CONSTRAINT user_tokens_pkey PRIMARY KEY (id);


--
-- Name: user_tokens user_tokens_token_hash_key; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.user_tokens
    ADD CONSTRAINT user_tokens_token_hash_key UNIQUE (token_hash);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: memo_jobs_in_flight; Type: INDEX; Schema: tier1; Owner: -
--

CREATE UNIQUE INDEX memo_jobs_in_flight ON tier1.memo_jobs USING btree (memo_id) WHERE ((collected_at IS NULL) AND (failure_code IS NULL));


--
-- Name: memo_jobs_key; Type: INDEX; Schema: tier1; Owner: -
--

CREATE UNIQUE INDEX memo_jobs_key ON tier1.memo_jobs USING btree (idempotency_key);


--
-- Name: memo_jobs_memo; Type: INDEX; Schema: tier1; Owner: -
--

CREATE INDEX memo_jobs_memo ON tier1.memo_jobs USING btree (memo_id);


--
-- Name: memo_proposals_memo; Type: INDEX; Schema: tier1; Owner: -
--

CREATE INDEX memo_proposals_memo ON tier1.memo_proposals USING btree (memo_id);


--
-- Name: memo_proposals_memo_proposer; Type: INDEX; Schema: tier1; Owner: -
--

CREATE UNIQUE INDEX memo_proposals_memo_proposer ON tier1.memo_proposals USING btree (memo_id, proposer);


--
-- Name: memo_proposals_needs_attention; Type: INDEX; Schema: tier1; Owner: -
--

CREATE INDEX memo_proposals_needs_attention ON tier1.memo_proposals USING btree (status, updated_at DESC) WHERE (status <> 'valid'::text);


--
-- Name: memo_uploads_activity; Type: INDEX; Schema: tier1; Owner: -
--

CREATE INDEX memo_uploads_activity ON tier1.memo_uploads USING btree (last_activity_at);


--
-- Name: memo_uploads_key; Type: INDEX; Schema: tier1; Owner: -
--

CREATE UNIQUE INDEX memo_uploads_key ON tier1.memo_uploads USING btree (author_id, idempotency_key);


--
-- Name: note_links_from; Type: INDEX; Schema: tier1; Owner: -
--

CREATE INDEX note_links_from ON tier1.note_links USING btree (from_note_id);


--
-- Name: note_links_to; Type: INDEX; Schema: tier1; Owner: -
--

CREATE INDEX note_links_to ON tier1.note_links USING btree (to_number);


--
-- Name: triage_holds_age; Type: INDEX; Schema: tier1; Owner: -
--

CREATE INDEX triage_holds_age ON tier1.triage_holds USING btree (held_at);


--
-- Name: watch_seen_content_hash; Type: INDEX; Schema: tier1; Owner: -
--

CREATE INDEX watch_seen_content_hash ON tier1.watch_seen USING btree (content_hash);


--
-- Name: memo_arrivals_key; Type: INDEX; Schema: tier2; Owner: -
--

CREATE UNIQUE INDEX memo_arrivals_key ON tier2.memo_arrivals USING btree (author_id, idempotency_key) WHERE (idempotency_key IS NOT NULL);


--
-- Name: memo_arrivals_memo; Type: INDEX; Schema: tier2; Owner: -
--

CREATE INDEX memo_arrivals_memo ON tier2.memo_arrivals USING btree (memo_id);


--
-- Name: memo_arrivals_sighting; Type: INDEX; Schema: tier2; Owner: -
--

CREATE UNIQUE INDEX memo_arrivals_sighting ON tier2.memo_arrivals USING btree (memo_id, source, source_ref) WHERE (idempotency_key IS NULL);


--
-- Name: memo_links_unresolved; Type: INDEX; Schema: tier2; Owner: -
--

CREATE INDEX memo_links_unresolved ON tier2.memo_links USING btree (created_at) WHERE ((confirmed_at IS NULL) AND (refused_at IS NULL));


--
-- Name: memos_author_content; Type: INDEX; Schema: tier2; Owner: -
--

CREATE UNIQUE INDEX memos_author_content ON tier2.memos USING btree (author_id, content_hash);


--
-- Name: note_deletions_note; Type: INDEX; Schema: tier2; Owner: -
--

CREATE INDEX note_deletions_note ON tier2.note_deletions USING btree (note_id, deleted_at DESC);


--
-- Name: note_deletions_open; Type: INDEX; Schema: tier2; Owner: -
--

CREATE UNIQUE INDEX note_deletions_open ON tier2.note_deletions USING btree (note_id) WHERE (undeleted_at IS NULL);


--
-- Name: note_revisions_fts; Type: INDEX; Schema: tier2; Owner: -
--

CREATE INDEX note_revisions_fts ON tier2.note_revisions USING gin (((setweight(to_tsvector('english'::regconfig, title), 'A'::"char") || setweight(to_tsvector('english'::regconfig, body), 'B'::"char"))));


--
-- Name: note_revisions_memo; Type: INDEX; Schema: tier2; Owner: -
--

CREATE UNIQUE INDEX note_revisions_memo ON tier2.note_revisions USING btree (memo_id) WHERE (memo_id IS NOT NULL);


--
-- Name: note_revisions_note; Type: INDEX; Schema: tier2; Owner: -
--

CREATE INDEX note_revisions_note ON tier2.note_revisions USING btree (note_id, seq DESC);


--
-- Name: note_tags_tag; Type: INDEX; Schema: tier2; Owner: -
--

CREATE INDEX note_tags_tag ON tier2.note_tags USING btree (tag);


--
-- Name: notes_page_live; Type: INDEX; Schema: tier2; Owner: -
--

CREATE INDEX notes_page_live ON tier2.notes USING btree (page_id) WHERE (deleted_at IS NULL);


--
-- Name: page_redirects_page; Type: INDEX; Schema: tier2; Owner: -
--

CREATE INDEX page_redirects_page ON tier2.page_redirects USING btree (page_id);


--
-- Name: pages_parent; Type: INDEX; Schema: tier2; Owner: -
--

CREATE INDEX pages_parent ON tier2.pages USING btree (parent_id);


--
-- Name: pages_root_slug; Type: INDEX; Schema: tier2; Owner: -
--

CREATE UNIQUE INDEX pages_root_slug ON tier2.pages USING btree (slug) WHERE (parent_id IS NULL);


--
-- Name: pages_sibling_slug; Type: INDEX; Schema: tier2; Owner: -
--

CREATE UNIQUE INDEX pages_sibling_slug ON tier2.pages USING btree (parent_id, slug) WHERE (parent_id IS NOT NULL);


--
-- Name: transcripts_durable; Type: INDEX; Schema: tier2; Owner: -
--

CREATE INDEX transcripts_durable ON tier2.transcripts USING btree (memo_id) WHERE (NOT partial);


--
-- Name: transcripts_fts; Type: INDEX; Schema: tier2; Owner: -
--

CREATE INDEX transcripts_fts ON tier2.transcripts USING gin (to_tsvector('english'::regconfig, text));


--
-- Name: transcripts_memo_model; Type: INDEX; Schema: tier2; Owner: -
--

CREATE UNIQUE INDEX transcripts_memo_model ON tier2.transcripts USING btree (memo_id, model);


--
-- Name: user_tokens_user_id; Type: INDEX; Schema: tier2; Owner: -
--

CREATE INDEX user_tokens_user_id ON tier2.user_tokens USING btree (user_id);


--
-- Name: users_single_owner; Type: INDEX; Schema: tier2; Owner: -
--

CREATE UNIQUE INDEX users_single_owner ON tier2.users USING btree (is_owner) WHERE is_owner;


--
-- Name: memo_proposals memo_proposals_guard; Type: TRIGGER; Schema: tier1; Owner: -
--

CREATE TRIGGER memo_proposals_guard BEFORE UPDATE ON tier1.memo_proposals FOR EACH ROW EXECUTE FUNCTION tier1.memo_proposals_guard();


--
-- Name: memo_links memo_links_guard; Type: TRIGGER; Schema: tier2; Owner: -
--

CREATE TRIGGER memo_links_guard BEFORE UPDATE ON tier2.memo_links FOR EACH ROW EXECUTE FUNCTION tier2.memo_links_guard();


--
-- Name: memos memos_guard; Type: TRIGGER; Schema: tier2; Owner: -
--

CREATE TRIGGER memos_guard BEFORE INSERT OR UPDATE ON tier2.memos FOR EACH ROW EXECUTE FUNCTION tier2.memos_guard();


--
-- Name: note_deletions note_deletions_guard; Type: TRIGGER; Schema: tier2; Owner: -
--

CREATE TRIGGER note_deletions_guard BEFORE INSERT OR DELETE OR UPDATE ON tier2.note_deletions FOR EACH ROW EXECUTE FUNCTION tier2.note_deletions_guard();


--
-- Name: note_revisions note_revisions_guard; Type: TRIGGER; Schema: tier2; Owner: -
--

CREATE TRIGGER note_revisions_guard BEFORE INSERT OR DELETE OR UPDATE ON tier2.note_revisions FOR EACH ROW EXECUTE FUNCTION tier2.note_revisions_guard();


--
-- Name: note_tags note_tags_guard; Type: TRIGGER; Schema: tier2; Owner: -
--

CREATE TRIGGER note_tags_guard BEFORE INSERT ON tier2.note_tags FOR EACH ROW EXECUTE FUNCTION tier2.note_tags_guard();


--
-- Name: notes notes_guard; Type: TRIGGER; Schema: tier2; Owner: -
--

CREATE TRIGGER notes_guard BEFORE INSERT OR UPDATE ON tier2.notes FOR EACH ROW EXECUTE FUNCTION tier2.notes_guard();


--
-- Name: pages pages_guard; Type: TRIGGER; Schema: tier2; Owner: -
--

CREATE TRIGGER pages_guard BEFORE INSERT OR UPDATE ON tier2.pages FOR EACH ROW EXECUTE FUNCTION tier2.pages_guard();


--
-- Name: transcripts transcripts_guard; Type: TRIGGER; Schema: tier2; Owner: -
--

CREATE TRIGGER transcripts_guard BEFORE INSERT OR UPDATE ON tier2.transcripts FOR EACH ROW EXECUTE FUNCTION tier2.transcripts_guard();


--
-- Name: memo_arrivals memo_arrivals_author_id_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.memo_arrivals
    ADD CONSTRAINT memo_arrivals_author_id_fkey FOREIGN KEY (author_id) REFERENCES tier2.users(id) ON DELETE RESTRICT;


--
-- Name: memo_arrivals memo_arrivals_memo_id_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.memo_arrivals
    ADD CONSTRAINT memo_arrivals_memo_id_fkey FOREIGN KEY (memo_id) REFERENCES tier2.memos(id) ON DELETE CASCADE;


--
-- Name: memo_links memo_links_memo_id_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.memo_links
    ADD CONSTRAINT memo_links_memo_id_fkey FOREIGN KEY (memo_id) REFERENCES tier2.memos(id) ON DELETE RESTRICT;


--
-- Name: memos memos_author_id_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.memos
    ADD CONSTRAINT memos_author_id_fkey FOREIGN KEY (author_id) REFERENCES tier2.users(id) ON DELETE RESTRICT;


--
-- Name: note_deletions note_deletions_deleted_by_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.note_deletions
    ADD CONSTRAINT note_deletions_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES tier2.users(id) ON DELETE RESTRICT;


--
-- Name: note_deletions note_deletions_note_id_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.note_deletions
    ADD CONSTRAINT note_deletions_note_id_fkey FOREIGN KEY (note_id) REFERENCES tier2.notes(id) ON DELETE RESTRICT;


--
-- Name: note_deletions note_deletions_undeleted_by_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.note_deletions
    ADD CONSTRAINT note_deletions_undeleted_by_fkey FOREIGN KEY (undeleted_by) REFERENCES tier2.users(id) ON DELETE RESTRICT;


--
-- Name: note_revisions note_revisions_author_id_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.note_revisions
    ADD CONSTRAINT note_revisions_author_id_fkey FOREIGN KEY (author_id) REFERENCES tier2.users(id) ON DELETE RESTRICT;


--
-- Name: note_revisions note_revisions_confirmed_by_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.note_revisions
    ADD CONSTRAINT note_revisions_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES tier2.users(id) ON DELETE RESTRICT;


--
-- Name: note_revisions note_revisions_memo_id_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.note_revisions
    ADD CONSTRAINT note_revisions_memo_id_fkey FOREIGN KEY (memo_id) REFERENCES tier2.memos(id) ON DELETE RESTRICT;


--
-- Name: note_revisions note_revisions_note_id_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.note_revisions
    ADD CONSTRAINT note_revisions_note_id_fkey FOREIGN KEY (note_id) REFERENCES tier2.notes(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;


--
-- Name: note_revisions note_revisions_restored_from; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.note_revisions
    ADD CONSTRAINT note_revisions_restored_from FOREIGN KEY (restored_from, note_id) REFERENCES tier2.note_revisions(id, note_id);


--
-- Name: note_tags note_tags_note_id_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.note_tags
    ADD CONSTRAINT note_tags_note_id_fkey FOREIGN KEY (note_id) REFERENCES tier2.notes(id) ON DELETE RESTRICT;


--
-- Name: notes notes_author_id_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.notes
    ADD CONSTRAINT notes_author_id_fkey FOREIGN KEY (author_id) REFERENCES tier2.users(id) ON DELETE RESTRICT;


--
-- Name: notes notes_current_revision; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.notes
    ADD CONSTRAINT notes_current_revision FOREIGN KEY (current_revision_id, id) REFERENCES tier2.note_revisions(id, note_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notes notes_deleted_by_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.notes
    ADD CONSTRAINT notes_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES tier2.users(id) ON DELETE RESTRICT;


--
-- Name: notes notes_page_id_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.notes
    ADD CONSTRAINT notes_page_id_fkey FOREIGN KEY (page_id) REFERENCES tier2.pages(id) ON DELETE RESTRICT;


--
-- Name: page_redirects page_redirects_page_id_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.page_redirects
    ADD CONSTRAINT page_redirects_page_id_fkey FOREIGN KEY (page_id) REFERENCES tier2.pages(id) ON DELETE RESTRICT;


--
-- Name: pages pages_parent_id_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.pages
    ADD CONSTRAINT pages_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES tier2.pages(id) ON DELETE RESTRICT;


--
-- Name: transcripts transcripts_memo_id_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.transcripts
    ADD CONSTRAINT transcripts_memo_id_fkey FOREIGN KEY (memo_id) REFERENCES tier2.memos(id) ON DELETE RESTRICT;


--
-- Name: user_tokens user_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: tier2; Owner: -
--

ALTER TABLE ONLY tier2.user_tokens
    ADD CONSTRAINT user_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES tier2.users(id) ON DELETE CASCADE;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: -
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- Name: SCHEMA tier1; Type: ACL; Schema: -; Owner: -
--

GRANT ALL ON SCHEMA tier1 TO chronicle_tier1;


--
-- Name: SCHEMA tier2; Type: ACL; Schema: -; Owner: -
--

GRANT USAGE ON SCHEMA tier2 TO chronicle_tier1;


--
-- Name: TABLE memo_jobs; Type: ACL; Schema: tier1; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE tier1.memo_jobs TO chronicle_tier1;


--
-- Name: TABLE memo_proposals; Type: ACL; Schema: tier1; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE tier1.memo_proposals TO chronicle_tier1;


--
-- Name: TABLE memo_uploads; Type: ACL; Schema: tier1; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE tier1.memo_uploads TO chronicle_tier1;


--
-- Name: TABLE note_links; Type: ACL; Schema: tier1; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE tier1.note_links TO chronicle_tier1;


--
-- Name: TABLE triage_holds; Type: ACL; Schema: tier1; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE tier1.triage_holds TO chronicle_tier1;


--
-- Name: TABLE watch_seen; Type: ACL; Schema: tier1; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE tier1.watch_seen TO chronicle_tier1;


--
-- Name: TABLE memos; Type: ACL; Schema: tier2; Owner: -
--

GRANT SELECT ON TABLE tier2.memos TO chronicle_tier1;


--
-- Name: TABLE transcripts; Type: ACL; Schema: tier2; Owner: -
--

GRANT SELECT ON TABLE tier2.transcripts TO chronicle_tier1;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: tier1; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA tier1 GRANT SELECT,USAGE ON SEQUENCES TO chronicle_tier1;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: tier1; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA tier1 GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO chronicle_tier1;


--
-- PostgreSQL database dump complete
--


