-- Generated by scripts/gen-schema.sh from migrations/. Do not edit.
-- Regenerate with: scripts/gen-schema.sh

--
-- PostgreSQL database dump
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: tier1; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA tier1;


--
-- Name: SCHEMA tier1; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA tier1 IS 'Tier 1 - derived and disposable. Chronicle''s account of what exists, and what it derives from its own corpus: proposals, entities, indexes. Regenerable from a source of truth outside these tables. Never hand-edited.';


--
-- Name: tier2; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA tier2;


--
-- Name: SCHEMA tier2; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA tier2 IS 'Tier 2 - authored and irreplaceable. What a person said or wrote: memos, transcripts, notes, discussions, plans. Not derivable from anything, cannot be rebuilt. Nothing on a tier-1 write path may reach these tables.';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version text NOT NULL,
    applied_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: -
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- Name: SCHEMA tier1; Type: ACL; Schema: -; Owner: -
--

GRANT ALL ON SCHEMA tier1 TO chronicle_tier1;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: tier1; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA tier1 GRANT SELECT,USAGE ON SEQUENCES TO chronicle_tier1;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: tier1; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA tier1 GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO chronicle_tier1;


--
-- PostgreSQL database dump complete
--


