// Package asrclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package asrclient

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for JobStatus.
const (
	JobStatusCancelled  JobStatus = "cancelled"
	JobStatusCancelling JobStatus = "cancelling"
	JobStatusFailed     JobStatus = "failed"
	JobStatusLeased     JobStatus = "leased"
	JobStatusQueued     JobStatus = "queued"
	JobStatusRunning    JobStatus = "running"
	JobStatusSucceeded  JobStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusCancelled:
		return true
	case JobStatusCancelling:
		return true
	case JobStatusFailed:
		return true
	case JobStatusLeased:
		return true
	case JobStatusQueued:
		return true
	case JobStatusRunning:
		return true
	case JobStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatus.
const (
	Ready   ReadinessStatus = "ready"
	Unready ReadinessStatus = "unready"
)

// Valid indicates whether the value is a known member of the ReadinessStatus enum.
func (e ReadinessStatus) Valid() bool {
	switch e {
	case Ready:
		return true
	case Unready:
		return true
	default:
		return false
	}
}

// Defines values for ResultStatus.
const (
	ResultStatusCancelled ResultStatus = "cancelled"
	ResultStatusFailed    ResultStatus = "failed"
	ResultStatusSucceeded ResultStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the ResultStatus enum.
func (e ResultStatus) Valid() bool {
	switch e {
	case ResultStatusCancelled:
		return true
	case ResultStatusFailed:
		return true
	case ResultStatusSucceeded:
		return true
	default:
		return false
	}
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	// AcceptedMediaTypes Example: ["audio/ogg","audio/webm","audio/mpeg","audio/mp4","audio/wav"]
	AcceptedMediaTypes []string `json:"accepted_media_types"`

	// DefaultModel Example: small.en
	DefaultModel string `json:"default_model"`

	// Models models this deployment has on disk and will run
	Models []string `json:"models"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Failure defines model for Failure.
type Failure struct {
	// Code Example: decode_failed
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Commit *string `json:"commit,omitempty"`

	// Status Example: ok
	Status  string  `json:"status"`
	Version *string `json:"version,omitempty"`
}

// Job defines model for Job.
type Job struct {
	// Attempts how many times this job has been claimed. Incremented by the reaper
	// when a lease expires. The CEILING and the backoff are CHRN-28's
	// policy; the counter lives here because the reaper moves it.
	Attempts  int                `json:"attempts"`
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Model     string             `json:"model"`

	// RetryAfterMs how long the client should wait before polling again. Absent on a
	// terminal job. Server-set, so a deep queue can back clients off
	// without a contract change.
	RetryAfterMs *int `json:"retry_after_ms,omitempty"`

	// Status Five stored states plus one derived. `leased` is separate from `running`
	// because they answer different questions: a worker has claimed the job,
	// versus inference has actually started — and a worker that dies between
	// the two needs different `attempts` accounting from one that died
	// mid-inference.
	//
	// `cancelling` is DERIVED — a `running` job whose cancellation has been
	// requested. It is in this enum despite not being a stored state because
	// it is observable by two codebases, and a status a client can see but
	// cannot find in the schema is a status one of them will fail to handle.
	Status    JobStatus `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
}

// JobSpec defines model for JobSpec.
type JobSpec struct {
	// AudioSha256 SHA-256 of the audio part, lowercase hex. Carried in the spec so the
	// idempotency mismatch check does not depend on having buffered the
	// body. A client that lies about it gets a job that transcribes bytes
	// the contract believes are something else — a client bug this service
	// cannot and should not defend against.
	AudioSha256 string `json:"audio_sha256"`

	// Language BCP-47 hint; omitted lets the model decide.
	Language *string `json:"language,omitempty"`

	// Model omitted takes the deployment default. A model this deployment does
	// not have is 400 rather than a job that fails later.
	Model *string `json:"model,omitempty"`
}

// JobStatus Five stored states plus one derived. `leased` is separate from `running`
// because they answer different questions: a worker has claimed the job,
// versus inference has actually started — and a worker that dies between
// the two needs different `attempts` accounting from one that died
// mid-inference.
//
// `cancelling` is DERIVED — a `running` job whose cancellation has been
// requested. It is in this enum despite not being a stored state because
// it is observable by two codebases, and a status a client can see but
// cannot find in the schema is a status one of them will fail to handle.
type JobStatus string

// Readiness defines model for Readiness.
type Readiness struct {
	// Check which dependency failed, when unready. `database`, `whisper_server`
	// when the resident process is absent or holds no model, or `standby`
	// when another process holds the device lock — a standby serves the
	// API correctly and cannot transcribe, and naming it keeps a second
	// asrd during a redeploy from reading as a broken one.
	Check *string `json:"check,omitempty"`

	// InferenceRunningMs how long the current inference has been running; absent when the
	// device is idle. Evidence for an operator, NOT a bound — the bound is
	// the per-job deadline the worker applies.
	InferenceRunningMs *int64 `json:"inference_running_ms,omitempty"`

	// QueueDepth jobs not yet in a terminal state
	QueueDepth *int64 `json:"queue_depth,omitempty"`

	// ResidentModel the model the resident worker is holding. Absent when nothing is
	// loaded, which is itself a reason this endpoint answers unready: a
	// service whose GPU has gone but whose database is fine would
	// otherwise report ready and accept work forever.
	ResidentModel *string         `json:"resident_model,omitempty"`
	Status        ReadinessStatus `json:"status"`
}

// ReadinessStatus defines model for Readiness.Status.
type ReadinessStatus string

// Result defines model for Result.
type Result struct {
	// AudioDurationMs as decoded
	AudioDurationMs *int64 `json:"audio_duration_ms,omitempty"`

	// Backend with `model`, stored alongside the transcript by the client — a
	// corpus transcribed by two different models over time is one whose
	// quality varies invisibly.
	//
	//
	// Example: vulkan
	Backend string `json:"backend"`

	// CoveredMs end of the last segment. EVIDENCE, NOT A PREDICATE. Useful when a
	// transcript looks short; never the gate. See `partial`.
	CoveredMs *int64             `json:"covered_ms,omitempty"`
	Failure   *Failure           `json:"failure,omitempty"`
	JobId     openapi_types.UUID `json:"job_id"`

	// Model Example: whisper.cpp/small.en
	Model string `json:"model"`

	// Partial A FACT THE SERVICE RECORDS about whether its own run completed. It
	// is never inferred by a client from `covered_ms < audio_duration_ms`
	// — whisper emits segments only where there is speech, so a memo with
	// five seconds of trailing silence has `covered_ms` short of the
	// duration on a perfectly complete run.
	//
	// A transcript is DURABLE iff its job reached `succeeded` and `partial`
	// is false. That predicate is what CHRN-22's retention pruner gates
	// audio deletion on, read from Chronicle's own transcript row rather
	// than from here.
	Partial  bool         `json:"partial"`
	Segments []Segment    `json:"segments"`
	Status   ResultStatus `json:"status"`

	// Text the transcript, timestamps stripped. EMPTY IS A VALID RESULT: a memo
	// that is forty seconds of silence has a true and complete answer, and
	// the answer is "no speech".
	Text string `json:"text"`
}

// ResultStatus defines model for Result.Status.
type ResultStatus string

// Segment defines model for Segment.
type Segment struct {
	EndMs   int64  `json:"end_ms"`
	StartMs int64  `json:"start_ms"`
	Text    string `json:"text"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// JobID defines model for JobID.
type JobID = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// SubmitJobMultipartBody defines parameters for SubmitJob.
type SubmitJobMultipartBody struct {
	// Audio The recording, in one of the accepted media types. The part
	// declares its own `Content-Type`; anything outside the
	// advertised set is 415.
	Audio openapi_types.File `json:"audio"`
	Spec  JobSpec            `json:"spec"`
}

// SubmitJobParams defines parameters for SubmitJob.
type SubmitJobParams struct {
	// IdempotencyKey Minted per transcription attempt and persisted before the request is
	// sent. Stable across HTTP retries of one attempt; fresh for a deliberate
	// re-transcription. Same name and same meaning as Chronicle's own ingest
	// key (CHRN-18) — one header, one meaning, across the estate.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// SubmitJobMultipartRequestBody defines body for SubmitJob for multipart/form-data ContentType.
type SubmitJobMultipartRequestBody SubmitJobMultipartBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetHealthz Liveness. No dependencies, no credential.
	//
	// Answers if the process is running. Deliberately free of dependencies:
	// a database that is down is not a reason to restart the binary.
	//
	// Corresponds with GET /healthz (the `GetHealthz` operationId).
	GetHealthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetReadyz Readiness. Pings the database, and reports the queue and the device.
	//
	// Corresponds with GET /readyz (the `GetReadyz` operationId).
	GetReadyz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SubmitJobWithBody Submit audio for transcription.
	//
	// `multipart/form-data` with two parts: `spec` (`application/json`) and
	// `audio`. Not a JSON body with the audio base64-encoded inside it — that
	// costs a third of the bytes and forces both ends to hold the whole thing
	// in memory to parse one field.
	//
	// `Idempotency-Key` is REQUIRED. It is minted per transcription attempt
	// and persisted by the client BEFORE the request is sent, so that an HTTP
	// retry of one attempt is a replay rather than a second job. Scoped to the
	// calling client, never expires.
	//
	// A replay — same key, same spec, same audio hash — answers 200 with the
	// existing job. A mismatch — same key, different audio hash or model —
	// answers 409, and the client mints a fresh key.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/jobs (the `SubmitJob` operationId).
	SubmitJobWithBody(ctx context.Context, params *SubmitJobParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetJob Job status. Cheap, safe to poll.
	//
	// Separate from the result so a 40-minute transcript is not re-sent every
	// two seconds. The response carries `retry_after_ms`: the SERVER sets poll
	// pressure, so a deep queue can back clients off without a contract change.
	//
	// Another client's job answers 404, not 403 — CHRN-71's precedent. A 403
	// confirms the id exists.
	//
	// Corresponds with GET /v1/jobs/{id} (the `GetJob` operationId).
	GetJob(ctx context.Context, id JobID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CancelJob Ask for the job to stop. Idempotent.
	//
	// POST and not DELETE because the job row SURVIVES cancellation — it is a
	// record that work was asked for and stopped, which DELETE would
	// misdescribe.
	//
	// `queued` and `leased` cancel immediately. A `running` job is marked and
	// the worker observes it; on the wire that job then reads `cancelling`.
	// An already-terminal job is a no-op returning 200 and its terminal state
	// — never a 409, because a client that crashed after cancelling and
	// retries must not be told off for having succeeded.
	//
	// Corresponds with POST /v1/jobs/{id}/cancel (the `CancelJob` operationId).
	CancelJob(ctx context.Context, id JobID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetJobResult Fetch the transcript.
	//
	// Fetched once, separately, and still here after a client crashes and
	// comes back. The payload is purged after the deployment's result TTL —
	// the JOB ROW survives that purge, which is what lets this answer 410
	// rather than 404: a client that comes back late learns its result
	// expired, not that its job never existed.
	//
	// "Result expired" is not "transcription failed". A client that gets a 410
	// re-submits with a fresh key.
	//
	// Corresponds with GET /v1/jobs/{id}/result (the `GetJobResult` operationId).
	GetJobResult(ctx context.Context, id JobID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListModels What this deployment can run, and what audio it accepts.
	//
	// So a client discovers rather than hardcodes. The accepted media types
	// live here rather than only in this document because a 415 a client
	// cannot enumerate its way out of is a 415 someone debugs by guessing.
	//
	// Corresponds with GET /v1/models (the `ListModels` operationId).
	ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetHealthz Liveness. No dependencies, no credential.
//
// Answers if the process is running. Deliberately free of dependencies:
// a database that is down is not a reason to restart the binary.
//
// Corresponds with GET /healthz (the `GetHealthz` operationId).
func (c *Client) GetHealthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthzRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetReadyz Readiness. Pings the database, and reports the queue and the device.
//
// Corresponds with GET /readyz (the `GetReadyz` operationId).
func (c *Client) GetReadyz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetReadyzRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SubmitJobWithBody Submit audio for transcription.
//
// `multipart/form-data` with two parts: `spec` (`application/json`) and
// `audio`. Not a JSON body with the audio base64-encoded inside it — that
// costs a third of the bytes and forces both ends to hold the whole thing
// in memory to parse one field.
//
// `Idempotency-Key` is REQUIRED. It is minted per transcription attempt
// and persisted by the client BEFORE the request is sent, so that an HTTP
// retry of one attempt is a replay rather than a second job. Scoped to the
// calling client, never expires.
//
// A replay — same key, same spec, same audio hash — answers 200 with the
// existing job. A mismatch — same key, different audio hash or model —
// answers 409, and the client mints a fresh key.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/jobs (the `SubmitJob` operationId).
func (c *Client) SubmitJobWithBody(ctx context.Context, params *SubmitJobParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubmitJobRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetJob Job status. Cheap, safe to poll.
//
// Separate from the result so a 40-minute transcript is not re-sent every
// two seconds. The response carries `retry_after_ms`: the SERVER sets poll
// pressure, so a deep queue can back clients off without a contract change.
//
// Another client's job answers 404, not 403 — CHRN-71's precedent. A 403
// confirms the id exists.
//
// Corresponds with GET /v1/jobs/{id} (the `GetJob` operationId).
func (c *Client) GetJob(ctx context.Context, id JobID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetJobRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CancelJob Ask for the job to stop. Idempotent.
//
// POST and not DELETE because the job row SURVIVES cancellation — it is a
// record that work was asked for and stopped, which DELETE would
// misdescribe.
//
// `queued` and `leased` cancel immediately. A `running` job is marked and
// the worker observes it; on the wire that job then reads `cancelling`.
// An already-terminal job is a no-op returning 200 and its terminal state
// — never a 409, because a client that crashed after cancelling and
// retries must not be told off for having succeeded.
//
// Corresponds with POST /v1/jobs/{id}/cancel (the `CancelJob` operationId).
func (c *Client) CancelJob(ctx context.Context, id JobID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelJobRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetJobResult Fetch the transcript.
//
// Fetched once, separately, and still here after a client crashes and
// comes back. The payload is purged after the deployment's result TTL —
// the JOB ROW survives that purge, which is what lets this answer 410
// rather than 404: a client that comes back late learns its result
// expired, not that its job never existed.
//
// "Result expired" is not "transcription failed". A client that gets a 410
// re-submits with a fresh key.
//
// Corresponds with GET /v1/jobs/{id}/result (the `GetJobResult` operationId).
func (c *Client) GetJobResult(ctx context.Context, id JobID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetJobResultRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListModels What this deployment can run, and what audio it accepts.
//
// So a client discovers rather than hardcodes. The accepted media types
// live here rather than only in this document because a 415 a client
// cannot enumerate its way out of is a 415 someone debugs by guessing.
//
// Corresponds with GET /v1/models (the `ListModels` operationId).
func (c *Client) ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListModelsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetHealthzRequest constructs an http.Request for the GetHealthz method
func NewGetHealthzRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetReadyzRequest constructs an http.Request for the GetReadyz method
func NewGetReadyzRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/readyz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSubmitJobRequestWithBody constructs an http.Request for the SubmitJob method, with any body, and a specified content type
func NewSubmitJobRequestWithBody(server string, params *SubmitJobParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/jobs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Idempotency-Key", headerParam0)

	}

	return req, nil
}

// NewGetJobRequest constructs an http.Request for the GetJob method
func NewGetJobRequest(server string, id JobID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/jobs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCancelJobRequest constructs an http.Request for the CancelJob method
func NewCancelJobRequest(server string, id JobID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/jobs/%s/cancel", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetJobResultRequest constructs an http.Request for the GetJobResult method
func NewGetJobResultRequest(server string, id JobID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/jobs/%s/result", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListModelsRequest constructs an http.Request for the ListModels method
func NewListModelsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/models")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetHealthzWithResponse Liveness. No dependencies, no credential.
	//
	// Answers if the process is running. Deliberately free of dependencies:
	// a database that is down is not a reason to restart the binary.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /healthz (the `GetHealthz` operationId).
	GetHealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthzResponse, error)

	// GetReadyzWithResponse Readiness. Pings the database, and reports the queue and the device.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /readyz (the `GetReadyz` operationId).
	GetReadyzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetReadyzResponse, error)

	// SubmitJobWithBodyWithResponse Submit audio for transcription.
	//
	// `multipart/form-data` with two parts: `spec` (`application/json`) and
	// `audio`. Not a JSON body with the audio base64-encoded inside it — that
	// costs a third of the bytes and forces both ends to hold the whole thing
	// in memory to parse one field.
	//
	// `Idempotency-Key` is REQUIRED. It is minted per transcription attempt
	// and persisted by the client BEFORE the request is sent, so that an HTTP
	// retry of one attempt is a replay rather than a second job. Scoped to the
	// calling client, never expires.
	//
	// A replay — same key, same spec, same audio hash — answers 200 with the
	// existing job. A mismatch — same key, different audio hash or model —
	// answers 409, and the client mints a fresh key.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/jobs (the `SubmitJob` operationId).
	SubmitJobWithBodyWithResponse(ctx context.Context, params *SubmitJobParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubmitJobResponse, error)

	// GetJobWithResponse Job status. Cheap, safe to poll.
	//
	// Separate from the result so a 40-minute transcript is not re-sent every
	// two seconds. The response carries `retry_after_ms`: the SERVER sets poll
	// pressure, so a deep queue can back clients off without a contract change.
	//
	// Another client's job answers 404, not 403 — CHRN-71's precedent. A 403
	// confirms the id exists.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/jobs/{id} (the `GetJob` operationId).
	GetJobWithResponse(ctx context.Context, id JobID, reqEditors ...RequestEditorFn) (*GetJobResponse, error)

	// CancelJobWithResponse Ask for the job to stop. Idempotent.
	//
	// POST and not DELETE because the job row SURVIVES cancellation — it is a
	// record that work was asked for and stopped, which DELETE would
	// misdescribe.
	//
	// `queued` and `leased` cancel immediately. A `running` job is marked and
	// the worker observes it; on the wire that job then reads `cancelling`.
	// An already-terminal job is a no-op returning 200 and its terminal state
	// — never a 409, because a client that crashed after cancelling and
	// retries must not be told off for having succeeded.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/jobs/{id}/cancel (the `CancelJob` operationId).
	CancelJobWithResponse(ctx context.Context, id JobID, reqEditors ...RequestEditorFn) (*CancelJobResponse, error)

	// GetJobResultWithResponse Fetch the transcript.
	//
	// Fetched once, separately, and still here after a client crashes and
	// comes back. The payload is purged after the deployment's result TTL —
	// the JOB ROW survives that purge, which is what lets this answer 410
	// rather than 404: a client that comes back late learns its result
	// expired, not that its job never existed.
	//
	// "Result expired" is not "transcription failed". A client that gets a 410
	// re-submits with a fresh key.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/jobs/{id}/result (the `GetJobResult` operationId).
	GetJobResultWithResponse(ctx context.Context, id JobID, reqEditors ...RequestEditorFn) (*GetJobResultResponse, error)

	// ListModelsWithResponse What this deployment can run, and what audio it accepts.
	//
	// So a client discovers rather than hardcodes. The accepted media types
	// live here rather than only in this document because a 415 a client
	// cannot enumerate its way out of is a 415 someone debugs by guessing.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/models (the `ListModels` operationId).
	ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error)
}

type GetHealthzResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Health
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetHealthzResponse) GetJSON200() *Health {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetHealthzResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetHealthzResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthzResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthzResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetReadyzResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Readiness
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Readiness
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetReadyzResponse) GetJSON200() *Readiness {
	return r.JSON200
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r GetReadyzResponse) GetJSON503() *Readiness {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r GetReadyzResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetReadyzResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetReadyzResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetReadyzResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SubmitJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Job
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Job
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON413 the response for an HTTP 413 `application/json` response
	JSON413 *Error
	// JSON415 the response for an HTTP 415 `application/json` response
	JSON415 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SubmitJobResponse) GetJSON200() *Job {
	return r.JSON200
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r SubmitJobResponse) GetJSON201() *Job {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r SubmitJobResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r SubmitJobResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r SubmitJobResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON413 returns the response for an HTTP 413 `application/json` response
func (r SubmitJobResponse) GetJSON413() *Error {
	return r.JSON413
}

// GetJSON415 returns the response for an HTTP 415 `application/json` response
func (r SubmitJobResponse) GetJSON415() *Error {
	return r.JSON415
}

// GetBody returns the raw response body bytes
func (r SubmitJobResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SubmitJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SubmitJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SubmitJobResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Job
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetJobResponse) GetJSON200() *Job {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetJobResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetJobResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r GetJobResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetJobResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CancelJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Job
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r CancelJobResponse) GetJSON200() *Job {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r CancelJobResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r CancelJobResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r CancelJobResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CancelJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CancelJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CancelJobResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetJobResultResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Result
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON410 the response for an HTTP 410 `application/json` response
	JSON410 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetJobResultResponse) GetJSON200() *Result {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetJobResultResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetJobResultResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r GetJobResultResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON410 returns the response for an HTTP 410 `application/json` response
func (r GetJobResultResponse) GetJSON410() *Error {
	return r.JSON410
}

// GetBody returns the raw response body bytes
func (r GetJobResultResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetJobResultResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetJobResultResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetJobResultResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListModelsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Capabilities
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListModelsResponse) GetJSON200() *Capabilities {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ListModelsResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r ListModelsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListModelsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListModelsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListModelsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetHealthzWithResponse Liveness. No dependencies, no credential.
//
// Answers if the process is running. Deliberately free of dependencies:
// a database that is down is not a reason to restart the binary.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /healthz (the `GetHealthz` operationId).
func (c *ClientWithResponses) GetHealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthzResponse, error) {
	rsp, err := c.GetHealthz(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthzResponse(rsp)
}

// GetReadyzWithResponse Readiness. Pings the database, and reports the queue and the device.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /readyz (the `GetReadyz` operationId).
func (c *ClientWithResponses) GetReadyzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetReadyzResponse, error) {
	rsp, err := c.GetReadyz(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetReadyzResponse(rsp)
}

// SubmitJobWithBodyWithResponse Submit audio for transcription.
//
// `multipart/form-data` with two parts: `spec` (`application/json`) and
// `audio`. Not a JSON body with the audio base64-encoded inside it — that
// costs a third of the bytes and forces both ends to hold the whole thing
// in memory to parse one field.
//
// `Idempotency-Key` is REQUIRED. It is minted per transcription attempt
// and persisted by the client BEFORE the request is sent, so that an HTTP
// retry of one attempt is a replay rather than a second job. Scoped to the
// calling client, never expires.
//
// A replay — same key, same spec, same audio hash — answers 200 with the
// existing job. A mismatch — same key, different audio hash or model —
// answers 409, and the client mints a fresh key.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/jobs (the `SubmitJob` operationId).
func (c *ClientWithResponses) SubmitJobWithBodyWithResponse(ctx context.Context, params *SubmitJobParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubmitJobResponse, error) {
	rsp, err := c.SubmitJobWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSubmitJobResponse(rsp)
}

// GetJobWithResponse Job status. Cheap, safe to poll.
//
// Separate from the result so a 40-minute transcript is not re-sent every
// two seconds. The response carries `retry_after_ms`: the SERVER sets poll
// pressure, so a deep queue can back clients off without a contract change.
//
// Another client's job answers 404, not 403 — CHRN-71's precedent. A 403
// confirms the id exists.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/jobs/{id} (the `GetJob` operationId).
func (c *ClientWithResponses) GetJobWithResponse(ctx context.Context, id JobID, reqEditors ...RequestEditorFn) (*GetJobResponse, error) {
	rsp, err := c.GetJob(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetJobResponse(rsp)
}

// CancelJobWithResponse Ask for the job to stop. Idempotent.
//
// POST and not DELETE because the job row SURVIVES cancellation — it is a
// record that work was asked for and stopped, which DELETE would
// misdescribe.
//
// `queued` and `leased` cancel immediately. A `running` job is marked and
// the worker observes it; on the wire that job then reads `cancelling`.
// An already-terminal job is a no-op returning 200 and its terminal state
// — never a 409, because a client that crashed after cancelling and
// retries must not be told off for having succeeded.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/jobs/{id}/cancel (the `CancelJob` operationId).
func (c *ClientWithResponses) CancelJobWithResponse(ctx context.Context, id JobID, reqEditors ...RequestEditorFn) (*CancelJobResponse, error) {
	rsp, err := c.CancelJob(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelJobResponse(rsp)
}

// GetJobResultWithResponse Fetch the transcript.
//
// Fetched once, separately, and still here after a client crashes and
// comes back. The payload is purged after the deployment's result TTL —
// the JOB ROW survives that purge, which is what lets this answer 410
// rather than 404: a client that comes back late learns its result
// expired, not that its job never existed.
//
// "Result expired" is not "transcription failed". A client that gets a 410
// re-submits with a fresh key.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/jobs/{id}/result (the `GetJobResult` operationId).
func (c *ClientWithResponses) GetJobResultWithResponse(ctx context.Context, id JobID, reqEditors ...RequestEditorFn) (*GetJobResultResponse, error) {
	rsp, err := c.GetJobResult(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetJobResultResponse(rsp)
}

// ListModelsWithResponse What this deployment can run, and what audio it accepts.
//
// So a client discovers rather than hardcodes. The accepted media types
// live here rather than only in this document because a 415 a client
// cannot enumerate its way out of is a 415 someone debugs by guessing.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/models (the `ListModels` operationId).
func (c *ClientWithResponses) ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error) {
	rsp, err := c.ListModels(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListModelsResponse(rsp)
}

// ParseGetHealthzResponse parses an HTTP response from a GetHealthzWithResponse call
func ParseGetHealthzResponse(rsp *http.Response) (*GetHealthzResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthzResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetReadyzResponse parses an HTTP response from a GetReadyzWithResponse call
func ParseGetReadyzResponse(rsp *http.Response) (*GetReadyzResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetReadyzResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Readiness
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Readiness
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseSubmitJobResponse parses an HTTP response from a SubmitJobWithResponse call
func ParseSubmitJobResponse(rsp *http.Response) (*SubmitJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SubmitJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Job
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Job
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	}

	return response, nil
}

// ParseGetJobResponse parses an HTTP response from a GetJobWithResponse call
func ParseGetJobResponse(rsp *http.Response) (*GetJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Job
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseCancelJobResponse parses an HTTP response from a CancelJobWithResponse call
func ParseCancelJobResponse(rsp *http.Response) (*CancelJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CancelJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Job
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetJobResultResponse parses an HTTP response from a GetJobResultWithResponse call
func ParseGetJobResultResponse(rsp *http.Response) (*GetJobResultResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetJobResultResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Result
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 410:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON410 = &dest

	}

	return response, nil
}

// ParseListModelsResponse parses an HTTP response from a ListModelsWithResponse call
func ParseListModelsResponse(rsp *http.Response) (*ListModelsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListModelsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Capabilities
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}
