//go:build go1.22

// Package wire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package wire

import (
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for MemoRetention.
const (
	MemoRetentionDays30     MemoRetention = "days_30"
	MemoRetentionDiscardNow MemoRetention = "discard_now"
	MemoRetentionForever    MemoRetention = "forever"
)

// Valid indicates whether the value is a known member of the MemoRetention enum.
func (e MemoRetention) Valid() bool {
	switch e {
	case MemoRetentionDays30:
		return true
	case MemoRetentionDiscardNow:
		return true
	case MemoRetentionForever:
		return true
	default:
		return false
	}
}

// Defines values for OpenUploadRequestRetention.
const (
	OpenUploadRequestRetentionDays30     OpenUploadRequestRetention = "days_30"
	OpenUploadRequestRetentionDiscardNow OpenUploadRequestRetention = "discard_now"
	OpenUploadRequestRetentionForever    OpenUploadRequestRetention = "forever"
)

// Valid indicates whether the value is a known member of the OpenUploadRequestRetention enum.
func (e OpenUploadRequestRetention) Valid() bool {
	switch e {
	case OpenUploadRequestRetentionDays30:
		return true
	case OpenUploadRequestRetentionDiscardNow:
		return true
	case OpenUploadRequestRetentionForever:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatus.
const (
	Ready   ReadinessStatus = "ready"
	Unready ReadinessStatus = "unready"
)

// Valid indicates whether the value is a known member of the ReadinessStatus enum.
func (e ReadinessStatus) Valid() bool {
	switch e {
	case Ready:
		return true
	case Unready:
		return true
	default:
		return false
	}
}

// Defines values for UploadStateStatus.
const (
	Complete   UploadStateStatus = "complete"
	Incomplete UploadStateStatus = "incomplete"
	Open       UploadStateStatus = "open"
)

// Valid indicates whether the value is a known member of the UploadStateStatus enum.
func (e UploadStateStatus) Valid() bool {
	switch e {
	case Complete:
		return true
	case Incomplete:
		return true
	case Open:
		return true
	default:
		return false
	}
}

// CorpusReport defines model for CorpusReport.
type CorpusReport struct {
	AudioPresent  int64      `json:"audio_present"`
	AudioPruned   int64      `json:"audio_pruned"`
	EverBytes     int64      `json:"ever_bytes"`
	Memos         int64      `json:"memos"`
	NewestCapture *time.Time `json:"newest_capture"`

	// OldestCapture Null on an empty corpus. Always present, so absent never means empty.
	OldestCapture *time.Time `json:"oldest_capture"`
	RecordedBytes int64      `json:"recorded_bytes"`
}

// DeviceSession defines model for DeviceSession.
type DeviceSession struct {
	CreatedAt time.Time `json:"created_at"`

	// Current Whether this is the session making the request. What lets a person
	// revoke every device but the one in their hand.
	Current     bool               `json:"current"`
	DeviceLabel string             `json:"device_label"`
	Id          openapi_types.UUID `json:"id"`
	LastSeenAt  *time.Time         `json:"last_seen_at"`
}

// DiskReport defines model for DiskReport.
type DiskReport struct {
	Bytes int64 `json:"bytes"`
	Files int   `json:"files"`

	// Staging Uploads in flight (CHRN-20) — files this service wrote and
	// understands, which are not recordings yet and may never become any.
	// Reported apart from both corpus and strays: counted as corpus it
	// would inflate what the memos cost, and counted as strays every phone
	// mid-upload would read as a file nobody can name.
	Staging      int   `json:"staging"`
	StagingBytes int64 `json:"staging_bytes"`
	StrayBytes   int64 `json:"stray_bytes"`

	// StraySample A sample of the stray paths. Strays are never counted as corpus and
	// never offered to the pruner.
	StraySample []string `json:"stray_sample,omitempty"`

	// Strays Files under the root that this layout did not write.
	Strays          int   `json:"strays"`
	VolumeFreeBytes int64 `json:"volume_free_bytes"`

	// VolumeKnown Whether the volume figures below were measurable. It is what
	// separates "not measured" from "measured as zero" — a full volume has
	// `volume_free_bytes: 0`, which is exactly when the figure matters
	// most, so neither number is ever omitted.
	VolumeKnown      bool  `json:"volume_known"`
	VolumeTotalBytes int64 `json:"volume_total_bytes"`
}

// Error defines model for Error.
type Error struct {
	// Code A stable machine token. Clients branch on this, never on `message`.
	//
	// Example: owner_only
	Code string `json:"code"`

	// Message One sentence, for a person. Not stable across releases.
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	// Commit Absent on a build that was not stamped with one.
	Commit  *string      `json:"commit,omitempty"`
	Status  HealthStatus `json:"status"`
	Version string       `json:"version"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// HeldMemo defines model for HeldMemo.
type HeldMemo struct {
	AuthorId   openapi_types.UUID `json:"author_id"`
	CapturedAt time.Time          `json:"captured_at"`
	Id         openapi_types.UUID `json:"id"`
	Reason     string             `json:"reason"`

	// Retry The exact command that releases this memo.
	Retry string `json:"retry"`
}

// Invite A single-use invite, shown once. `sign_in_url` is the QR target and is
// absent when this deployment has no mobile base URL configured — a link
// built from the Access-gated host would walk a phone into an SSO wall a
// bearer token cannot open.
type Invite struct {
	// ExpiresIn How long the invite is good for, as a Go duration string.
	//
	// Example: 24h0m0s
	ExpiresIn   string  `json:"expires_in"`
	InviteToken string  `json:"invite_token"`
	SignInUrl   *string `json:"sign_in_url,omitempty"`

	// User An account, as the wire carries it. It deliberately holds **no token
	// material**: a credential is returned exactly once, by the call that
	// mints it.
	User User `json:"user"`
}

// Member An account with what the owner needs to administer it. `last_seen_at`
// null and `invite_expires_at` set is an invite never redeemed.
type Member struct {
	DisplayName     string             `json:"display_name"`
	Email           string             `json:"email"`
	Id              openapi_types.UUID `json:"id"`
	InviteExpiresAt *time.Time         `json:"invite_expires_at"`
	IsOwner         bool               `json:"is_owner"`
	Kind            string             `json:"kind"`
	LastSeenAt      *time.Time         `json:"last_seen_at"`
	SessionCount    int                `json:"session_count"`
}

// Memo A captured recording. **Tier 2**: what a person said, derivable from
// nothing, rebuildable by nobody.
type Memo struct {
	// AudioPruned The recording is gone and the transcript remains. Never true without
	// a durable transcript — that predicate, not the calendar, is what
	// gates deletion.
	AudioPruned bool      `json:"audio_pruned"`
	ByteSize    int64     `json:"byte_size"`
	CapturedAt  time.Time `json:"captured_at"`
	Codec       *string   `json:"codec"`
	ContentHash string    `json:"content_hash"`

	// DurationMs Null until something has decoded the file; a declaration is not a measurement.
	DurationMs       *int32             `json:"duration_ms"`
	Id               openapi_types.UUID `json:"id"`
	OriginalFilename *string            `json:"original_filename,omitempty"`

	// PrunesAt When, on that clause. Null when nothing will prune it.
	PrunesAt  *time.Time    `json:"prunes_at"`
	Retention MemoRetention `json:"retention"`

	// RetentionStatus What will happen to this memo's audio — the same clause the pruner sweeps with.
	RetentionStatus string `json:"retention_status"`
	SampleRateHz    *int32 `json:"sample_rate_hz"`

	// State captured, queued, transcribing, transcribed, held, discarded.
	State string `json:"state"`
}

// MemoRetention defines model for Memo.Retention.
type MemoRetention string

// Mismatch defines model for Mismatch.
type Mismatch struct {
	OnDiskBytes   int64 `json:"on_disk_bytes"`
	RecordedBytes int64 `json:"recorded_bytes"`

	// Ref `<author-id>/<content-hash>`.
	Ref string `json:"ref"`
}

// NewUserRequest defines model for NewUserRequest.
type NewUserRequest struct {
	DisplayName *string `json:"display_name,omitempty"`

	// Email Also the Access identity this account is matched to on SSO.
	Email string `json:"email"`

	// Kind `person` or `agent`. An agent account can hold a token but is never
	// an owner and never confirms authored text — `note_revisions_guard`
	// refuses any revision whose `confirmed_by` names one.
	Kind *string `json:"kind,omitempty"`
}

// OpenUploadRequest defines model for OpenUploadRequest.
type OpenUploadRequest struct {
	ByteSize int64 `json:"byte_size"`

	// ContentHash SHA-256 of the file, lowercase hex. Checked on completion: bytes
	// that do not match it are discarded rather than stored as a memo
	// nobody can verify.
	ContentHash string `json:"content_hash"`

	// IdempotencyKey Minted per capture and persisted by the client BEFORE the request
	// goes out, so an HTTP retry is a replay rather than a second memo.
	IdempotencyKey   string  `json:"idempotency_key"`
	OriginalFilename *string `json:"original_filename,omitempty"`

	// Retention Omitted means the deployment default. `days_30` is pruned by policy
	// once a durable transcript exists — never on the calendar alone,
	// because pruning audio whose transcription never succeeded is
	// unrecoverable loss with no user-visible warning.
	Retention *OpenUploadRequestRetention `json:"retention,omitempty"`
}

// OpenUploadRequestRetention Omitted means the deployment default. `days_30` is pruned by policy
// once a durable transcript exists — never on the calendar alone,
// because pruning audio whose transcription never succeeded is
// unrecoverable loss with no user-visible warning.
type OpenUploadRequestRetention string

// PartialTranscript defines model for PartialTranscript.
type PartialTranscript struct {
	MemoId openapi_types.UUID `json:"memo_id"`

	// Model Runner-qualified, e.g. `whisper.cpp/small.en`.
	Model         string    `json:"model"`
	TranscribedAt time.Time `json:"transcribed_at"`
}

// Readiness defines model for Readiness.
type Readiness struct {
	// Check Which dependency failed. Present only on `unready`, and naming the
	// check rather than the error: the detail belongs in the log, not in a
	// body that may cross the WAN.
	//
	//
	// Example: database
	Check  *string         `json:"check,omitempty"`
	Status ReadinessStatus `json:"status"`
}

// ReadinessStatus defines model for Readiness.Status.
type ReadinessStatus string

// ReconciliationReport defines model for ReconciliationReport.
type ReconciliationReport struct {
	Mismatched int `json:"mismatched"`

	// MismatchedSample Carries both sizes. Without them a 5-against-4096 truncation and a
	// 4097-against-4096 rounding read identically, and those are not the
	// same finding.
	MismatchedSample []Mismatch `json:"mismatched_sample,omitempty"`

	// Missing **The direction that matters.** A memo says its audio is present and
	// the file is not there. Non-zero here is the unrecoverable loss
	// CLAUDE.md names as the worst thing this system can do, and it leaves
	// a log line whether or not anybody reads this response.
	Missing       int      `json:"missing"`
	MissingBytes  int64    `json:"missing_bytes"`
	MissingSample []string `json:"missing_sample,omitempty"`
	OrphanBytes   int64    `json:"orphan_bytes"`
	OrphanSample  []string `json:"orphan_sample,omitempty"`

	// Orphans Audio on disk that no memo claims.
	Orphans int `json:"orphans"`
}

// Session A signed-in session. `session_token` is shown HERE AND NEVER AGAIN —
// there is no endpoint that returns it a second time, because it is stored
// hashed.
type Session struct {
	SessionToken string `json:"session_token"`

	// User An account, as the wire carries it. It deliberately holds **no token
	// material**: a credential is returned exactly once, by the call that
	// mints it.
	User User `json:"user"`
}

// SignInRequest defines model for SignInRequest.
type SignInRequest struct {
	// DeviceLabel What this device is called in the session list its holder reads.
	// Optional, and bounded — it reaches a TEXT column with no length of
	// its own.
	DeviceLabel *string `json:"device_label,omitempty"`

	// Token A single-use invite token.
	Token string `json:"token"`
}

// SsoError The Access path's error, which carries one field more than the shared
// envelope: the **email the assertion named**. Without it a person facing
// an SSO wall cannot tell which identity was rejected, and that is the
// whole question they have.
//
// `code` rather than `error`: the handler's own vocabulary has always
// called it a code, and two names for one concept in one document is the
// drift this contract exists to remove.
type SsoError struct {
	// Code Example: no_account
	Code string `json:"code"`

	// Email The verified email the assertion named. Absent when there was no assertion to read.
	Email   *string `json:"email,omitempty"`
	Message string  `json:"message"`
}

// StorageReport defines model for StorageReport.
type StorageReport struct {
	Corpus         CorpusReport         `json:"corpus"`
	Disk           DiskReport           `json:"disk"`
	Reconciliation ReconciliationReport `json:"reconciliation"`

	// Root The audio store's root on disk.
	Root   string       `json:"root"`
	Window WindowReport `json:"window"`
}

// TranscriptionReport defines model for TranscriptionReport.
type TranscriptionReport struct {
	// Enabled Whether a transcription pump is configured at all. Without it, an
	// operator reading `pending: 812` cannot tell a backlog from a service
	// that was never pointed at an ASR endpoint — and those want
	// completely different remedies.
	Enabled    bool       `json:"enabled"`
	Held       int64      `json:"held"`
	HeldSample []HeldMemo `json:"held_sample,omitempty"`

	// Partial Memos whose only transcript is incomplete. Reported because they are
	// otherwise INVISIBLE: a partial memo is `transcribed`, so nothing
	// sweeps it; it is not `held`, so `chronicle retranscribe` will not
	// release it; and its audio correctly does not prune. Every one of
	// those is right, and together they make a partial memo read as a
	// healthy one.
	Partial       int64               `json:"partial"`
	PartialSample []PartialTranscript `json:"partial_sample,omitempty"`

	// Pending Captured, queued and transcribing together. One number, because "how
	// far behind is it" is the question being asked.
	Pending int64 `json:"pending"`

	// States Every memo counted by state, not only the interesting ones. A report
	// naming only `held` could not tell "nothing is wrong" from "nothing
	// is happening", and a pump that has silently stopped looks exactly
	// like a corpus with no failures.
	States map[string]int64 `json:"states"`
}

// UpdateMeRequest defines model for UpdateMeRequest.
type UpdateMeRequest struct {
	DisplayName string `json:"display_name"`
}

// UploadState Where an upload got to. The same shape answers the successful cases and
// the two that carry a resume instruction (409, 408), so a client has one
// thing to parse.
type UploadState struct {
	ByteSize int64 `json:"byte_size"`

	// Duplicate Whether this declaration matched a memo that already exists. A
	// replay is a success, not a conflict.
	Duplicate bool       `json:"duplicate"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// Memo A captured recording. **Tier 2**: what a person said, derivable from
	// nothing, rebuildable by nobody.
	Memo *Memo `json:"memo,omitempty"`

	// Offset How many bytes the server holds. Send from here next.
	Offset   int64             `json:"offset"`
	Status   UploadStateStatus `json:"status"`
	UploadId *string           `json:"upload_id,omitempty"`
}

// UploadStateStatus defines model for UploadState.Status.
type UploadStateStatus string

// User An account, as the wire carries it. It deliberately holds **no token
// material**: a credential is returned exactly once, by the call that
// mints it.
type User struct {
	DisplayName string             `json:"display_name"`
	Email       string             `json:"email"`
	Id          openapi_types.UUID `json:"id"`
	IsOwner     bool               `json:"is_owner"`
	Kind        string             `json:"kind"`
}

// WindowReport defines model for WindowReport.
type WindowReport struct {
	Bytes          int64   `json:"bytes"`
	Days           int     `json:"days"`
	Memos          int64   `json:"memos"`
	PctOfProjected float64 `json:"pct_of_projected"`

	// ProjectedBytes What the sizing in docs/benchmarks projected for this window.
	ProjectedBytes int64 `json:"projected_bytes"`
}

// SessionId defines model for SessionId.
type SessionId = openapi_types.UUID

// UploadId defines model for UploadId.
type UploadId = openapi_types.UUID

// UserId defines model for UserId.
type UserId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// RateLimited defines model for RateLimited.
type RateLimited = Error

// TooLarge defines model for TooLarge.
type TooLarge = Error

// TransferCut Where an upload got to. The same shape answers the successful cases and
// the two that carry a resume instruction (409, 408), so a client has one
// thing to parse.
type TransferCut = UploadState

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unprocessable defines model for Unprocessable.
type Unprocessable = Error

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = Error

// UploadConflict Where an upload got to. The same shape answers the successful cases and
// the two that carry a resume instruction (409, 408), so a client has one
// thing to parse.
type UploadConflict = UploadState

// UploadsUnconfigured defines model for UploadsUnconfigured.
type UploadsUnconfigured = Error

// AppendChunkParams defines parameters for AppendChunk.
type AppendChunkParams struct {
	// UploadOffset The offset these bytes start at. A disagreement answers 409 carrying the server's.
	UploadOffset int64 `json:"Upload-Offset"`
}

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = NewUserRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateMeRequest

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = SignInRequest

// OpenUploadJSONRequestBody defines body for OpenUpload for application/json ContentType.
type OpenUploadJSONRequestBody = OpenUploadRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetStorageReport What the corpus costs, and whether the disk agrees with the database.
	// (GET /admin/storage)
	GetStorageReport(w http.ResponseWriter, r *http.Request)
	// GetTranscriptionReport How transcription is going, and which memos are stuck.
	// (GET /admin/transcription)
	GetTranscriptionReport(w http.ResponseWriter, r *http.Request)
	// ListUsers Every account, with its devices and invite state.
	// (GET /admin/users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// CreateUser Create an account and mint its first invite.
	// (POST /admin/users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// DeleteUser Remove an account and its credentials.
	// (DELETE /admin/users/{id})
	DeleteUser(w http.ResponseWriter, r *http.Request, id UserId)
	// CreateUserInvite Mint a fresh invite for an existing account.
	// (POST /admin/users/{id}/invite)
	CreateUserInvite(w http.ResponseWriter, r *http.Request, id UserId)
	// CreateSelfInvite Mint an invite for another of your own devices.
	// (POST /auth/invite)
	CreateSelfInvite(w http.ResponseWriter, r *http.Request)
	// GetMe The account this session belongs to.
	// (GET /auth/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// UpdateMe Change your own display name.
	// (PATCH /auth/me)
	UpdateMe(w http.ResponseWriter, r *http.Request)
	// DeleteSession Sign out, revoking this session.
	// (DELETE /auth/session)
	DeleteSession(w http.ResponseWriter, r *http.Request)
	// CreateSession Redeem an invite for a session.
	// (POST /auth/session)
	CreateSession(w http.ResponseWriter, r *http.Request)
	// ListSessions Your own signed-in devices.
	// (GET /auth/sessions)
	ListSessions(w http.ResponseWriter, r *http.Request)
	// RevokeSession Revoke one of your own sessions.
	// (DELETE /auth/sessions/{id})
	RevokeSession(w http.ResponseWriter, r *http.Request, id SessionId)
	// CreateSessionFromAccess Exchange a verified Cloudflare Access identity for a session.
	// (POST /auth/sso/cloudflare)
	CreateSessionFromAccess(w http.ResponseWriter, r *http.Request)
	// GetHealthz Liveness. No dependencies, no credential.
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// OpenUpload Declare an upload and open a session for it.
	// (POST /memos/uploads)
	OpenUpload(w http.ResponseWriter, r *http.Request)
	// AbandonUpload Abandon an upload and discard its staged bytes.
	// (DELETE /memos/uploads/{id})
	AbandonUpload(w http.ResponseWriter, r *http.Request, id UploadId)
	// GetUpload Where this upload got to.
	// (GET /memos/uploads/{id})
	GetUpload(w http.ResponseWriter, r *http.Request, id UploadId)
	// AppendChunk Append a chunk.
	// (PATCH /memos/uploads/{id})
	AppendChunk(w http.ResponseWriter, r *http.Request, id UploadId, params AppendChunkParams)
	// GetReadyz Readiness. Pings the database.
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetStorageReport operation middleware
func (siw *ServerInterfaceWrapper) GetStorageReport(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStorageReport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTranscriptionReport operation middleware
func (siw *ServerInterfaceWrapper) GetTranscriptionReport(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTranscriptionReport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id UserId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUserInvite operation middleware
func (siw *ServerInterfaceWrapper) CreateUserInvite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id UserId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUserInvite(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSelfInvite operation middleware
func (siw *ServerInterfaceWrapper) CreateSelfInvite(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSelfInvite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMe operation middleware
func (siw *ServerInterfaceWrapper) UpdateMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeSession operation middleware
func (siw *ServerInterfaceWrapper) RevokeSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeSession(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSessionFromAccess operation middleware
func (siw *ServerInterfaceWrapper) CreateSessionFromAccess(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSessionFromAccess(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OpenUpload operation middleware
func (siw *ServerInterfaceWrapper) OpenUpload(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OpenUpload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AbandonUpload operation middleware
func (siw *ServerInterfaceWrapper) AbandonUpload(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id UploadId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AbandonUpload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUpload operation middleware
func (siw *ServerInterfaceWrapper) GetUpload(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id UploadId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUpload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AppendChunk operation middleware
func (siw *ServerInterfaceWrapper) AppendChunk(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id UploadId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params AppendChunkParams

	headers := r.Header

	// ------------- Required header parameter "Upload-Offset" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Upload-Offset")]; found {
		var UploadOffset int64
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Upload-Offset", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Upload-Offset", valueList[0], &UploadOffset, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "integer", Format: "int64"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Upload-Offset", Err: err})
			return
		}

		params.UploadOffset = UploadOffset

	} else {
		err := fmt.Errorf("Header parameter Upload-Offset is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Upload-Offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AppendChunk(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.GetReadyz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/admin/storage", wrapper.GetStorageReport)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/admin/transcription", wrapper.GetTranscriptionReport)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/auth/session", wrapper.DeleteSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/session", wrapper.CreateSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/sso/cloudflare", wrapper.CreateSessionFromAccess)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/me", wrapper.GetMe)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/auth/me", wrapper.UpdateMe)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/invite", wrapper.CreateSelfInvite)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/sessions", wrapper.ListSessions)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/auth/sessions/{id}", wrapper.RevokeSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/admin/users", wrapper.ListUsers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/admin/users", wrapper.CreateUser)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/admin/users/{id}/invite", wrapper.CreateUserInvite)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/admin/users/{id}", wrapper.DeleteUser)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/memos/uploads", wrapper.OpenUpload)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/memos/uploads/{id}", wrapper.AbandonUpload)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/memos/uploads/{id}", wrapper.GetUpload)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/memos/uploads/{id}", wrapper.AppendChunk)

	return m
}
