//go:build go1.22

// Package wire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package wire

import (
	"fmt"
	"net/http"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatus.
const (
	Ready   ReadinessStatus = "ready"
	Unready ReadinessStatus = "unready"
)

// Valid indicates whether the value is a known member of the ReadinessStatus enum.
func (e ReadinessStatus) Valid() bool {
	switch e {
	case Ready:
		return true
	case Unready:
		return true
	default:
		return false
	}
}

// CorpusReport defines model for CorpusReport.
type CorpusReport struct {
	AudioPresent  int64      `json:"audio_present"`
	AudioPruned   int64      `json:"audio_pruned"`
	EverBytes     int64      `json:"ever_bytes"`
	Memos         int64      `json:"memos"`
	NewestCapture *time.Time `json:"newest_capture"`

	// OldestCapture Null on an empty corpus. Always present, so absent never means empty.
	OldestCapture *time.Time `json:"oldest_capture"`
	RecordedBytes int64      `json:"recorded_bytes"`
}

// DiskReport defines model for DiskReport.
type DiskReport struct {
	Bytes int64 `json:"bytes"`
	Files int   `json:"files"`

	// Staging Uploads in flight (CHRN-20) — files this service wrote and
	// understands, which are not recordings yet and may never become any.
	// Reported apart from both corpus and strays: counted as corpus it
	// would inflate what the memos cost, and counted as strays every phone
	// mid-upload would read as a file nobody can name.
	Staging      int   `json:"staging"`
	StagingBytes int64 `json:"staging_bytes"`
	StrayBytes   int64 `json:"stray_bytes"`

	// StraySample A sample of the stray paths. Strays are never counted as corpus and
	// never offered to the pruner.
	StraySample []string `json:"stray_sample,omitempty"`

	// Strays Files under the root that this layout did not write.
	Strays          int   `json:"strays"`
	VolumeFreeBytes int64 `json:"volume_free_bytes"`

	// VolumeKnown Whether the volume figures below were measurable. It is what
	// separates "not measured" from "measured as zero" — a full volume has
	// `volume_free_bytes: 0`, which is exactly when the figure matters
	// most, so neither number is ever omitted.
	VolumeKnown      bool  `json:"volume_known"`
	VolumeTotalBytes int64 `json:"volume_total_bytes"`
}

// Error defines model for Error.
type Error struct {
	// Code A stable machine token. Clients branch on this, never on `message`.
	//
	// Example: owner_only
	Code string `json:"code"`

	// Message One sentence, for a person. Not stable across releases.
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	// Commit Absent on a build that was not stamped with one.
	Commit  *string      `json:"commit,omitempty"`
	Status  HealthStatus `json:"status"`
	Version string       `json:"version"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// HeldMemo defines model for HeldMemo.
type HeldMemo struct {
	AuthorId   openapi_types.UUID `json:"author_id"`
	CapturedAt time.Time          `json:"captured_at"`
	Id         openapi_types.UUID `json:"id"`
	Reason     string             `json:"reason"`

	// Retry The exact command that releases this memo.
	Retry string `json:"retry"`
}

// Mismatch defines model for Mismatch.
type Mismatch struct {
	OnDiskBytes   int64 `json:"on_disk_bytes"`
	RecordedBytes int64 `json:"recorded_bytes"`

	// Ref `<author-id>/<content-hash>`.
	Ref string `json:"ref"`
}

// PartialTranscript defines model for PartialTranscript.
type PartialTranscript struct {
	MemoId openapi_types.UUID `json:"memo_id"`

	// Model Runner-qualified, e.g. `whisper.cpp/small.en`.
	Model         string    `json:"model"`
	TranscribedAt time.Time `json:"transcribed_at"`
}

// Readiness defines model for Readiness.
type Readiness struct {
	// Check Which dependency failed. Present only on `unready`, and naming the
	// check rather than the error: the detail belongs in the log, not in a
	// body that may cross the WAN.
	//
	//
	// Example: database
	Check  *string         `json:"check,omitempty"`
	Status ReadinessStatus `json:"status"`
}

// ReadinessStatus defines model for Readiness.Status.
type ReadinessStatus string

// ReconciliationReport defines model for ReconciliationReport.
type ReconciliationReport struct {
	Mismatched int `json:"mismatched"`

	// MismatchedSample Carries both sizes. Without them a 5-against-4096 truncation and a
	// 4097-against-4096 rounding read identically, and those are not the
	// same finding.
	MismatchedSample []Mismatch `json:"mismatched_sample,omitempty"`

	// Missing **The direction that matters.** A memo says its audio is present and
	// the file is not there. Non-zero here is the unrecoverable loss
	// CLAUDE.md names as the worst thing this system can do, and it leaves
	// a log line whether or not anybody reads this response.
	Missing       int      `json:"missing"`
	MissingBytes  int64    `json:"missing_bytes"`
	MissingSample []string `json:"missing_sample,omitempty"`
	OrphanBytes   int64    `json:"orphan_bytes"`
	OrphanSample  []string `json:"orphan_sample,omitempty"`

	// Orphans Audio on disk that no memo claims.
	Orphans int `json:"orphans"`
}

// StorageReport defines model for StorageReport.
type StorageReport struct {
	Corpus         CorpusReport         `json:"corpus"`
	Disk           DiskReport           `json:"disk"`
	Reconciliation ReconciliationReport `json:"reconciliation"`

	// Root The audio store's root on disk.
	Root   string       `json:"root"`
	Window WindowReport `json:"window"`
}

// TranscriptionReport defines model for TranscriptionReport.
type TranscriptionReport struct {
	// Enabled Whether a transcription pump is configured at all. Without it, an
	// operator reading `pending: 812` cannot tell a backlog from a service
	// that was never pointed at an ASR endpoint — and those want
	// completely different remedies.
	Enabled    bool       `json:"enabled"`
	Held       int64      `json:"held"`
	HeldSample []HeldMemo `json:"held_sample,omitempty"`

	// Partial Memos whose only transcript is incomplete. Reported because they are
	// otherwise INVISIBLE: a partial memo is `transcribed`, so nothing
	// sweeps it; it is not `held`, so `chronicle retranscribe` will not
	// release it; and its audio correctly does not prune. Every one of
	// those is right, and together they make a partial memo read as a
	// healthy one.
	Partial       int64               `json:"partial"`
	PartialSample []PartialTranscript `json:"partial_sample,omitempty"`

	// Pending Captured, queued and transcribing together. One number, because "how
	// far behind is it" is the question being asked.
	Pending int64 `json:"pending"`

	// States Every memo counted by state, not only the interesting ones. A report
	// naming only `held` could not tell "nothing is wrong" from "nothing
	// is happening", and a pump that has silently stopped looks exactly
	// like a corpus with no failures.
	States map[string]int64 `json:"states"`
}

// WindowReport defines model for WindowReport.
type WindowReport struct {
	Bytes          int64   `json:"bytes"`
	Days           int     `json:"days"`
	Memos          int64   `json:"memos"`
	PctOfProjected float64 `json:"pct_of_projected"`

	// ProjectedBytes What the sizing in docs/benchmarks projected for this window.
	ProjectedBytes int64 `json:"projected_bytes"`
}

// Forbidden defines model for Forbidden.
type Forbidden = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetStorageReport What the corpus costs, and whether the disk agrees with the database.
	// (GET /admin/storage)
	GetStorageReport(w http.ResponseWriter, r *http.Request)
	// GetTranscriptionReport How transcription is going, and which memos are stuck.
	// (GET /admin/transcription)
	GetTranscriptionReport(w http.ResponseWriter, r *http.Request)
	// GetHealthz Liveness. No dependencies, no credential.
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// GetReadyz Readiness. Pings the database.
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetStorageReport operation middleware
func (siw *ServerInterfaceWrapper) GetStorageReport(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStorageReport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTranscriptionReport operation middleware
func (siw *ServerInterfaceWrapper) GetTranscriptionReport(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTranscriptionReport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.GetReadyz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/admin/storage", wrapper.GetStorageReport)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/admin/transcription", wrapper.GetTranscriptionReport)

	return m
}
