#!/usr/bin/env bash
# Regenerate schema.sql from the migrations.
#
# schema.sql is a GENERATED artefact: the schema you get by applying every
# migration in order to an empty database. CI regenerates it and fails if the
# result differs from what is committed, which is what stops the two drifting.
# Catenary's R4 spent a whole gate learning that a generated artefact with no
# guard is one somebody hand-edits.
#
#   SCHEMAGEN_SUPERUSER_DSN=postgres://postgres:pw@127.0.0.1:5432/postgres?sslmode=disable \
#     scripts/gen-schema.sh
#
# psql and pg_dump run from a PINNED image rather than whatever the host has,
# because pg_dump output varies between versions and the whole point is a
# byte-comparable file.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

: "${SCHEMAGEN_SUPERUSER_DSN:?set it to a superuser DSN on the postgres to build against}"
PG_IMAGE="${PG_IMAGE:-postgres:16.15-alpine}"
SCRATCH="${SCHEMAGEN_DB:-chronicle_schemagen}"
OUT="${SCHEMAGEN_OUT:-schema.sql}"

pg() { docker run --rm --network host -i "$PG_IMAGE" "$@"; }

# The scratch database is dropped and rebuilt every run: the artefact must
# describe the migrations alone, never leftover state from a previous run.
pg psql "$SCHEMAGEN_SUPERUSER_DSN" -v ON_ERROR_STOP=1 -q <<SQL
DROP DATABASE IF EXISTS ${SCRATCH};
SELECT 'CREATE ROLE chronicle LOGIN' WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='chronicle');
\gexec
SELECT 'CREATE ROLE chronicle_tier1 LOGIN' WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='chronicle_tier1');
\gexec
CREATE DATABASE ${SCRATCH} OWNER chronicle;
SQL

# Apply via the real migrator, so this also proves the migrator and the files
# agree — not just that the SQL parses.
scratch_dsn="$(printf '%s' "$SCHEMAGEN_SUPERUSER_DSN" | sed "s#/postgres?#/${SCRATCH}?#")"
CHRONICLE_DATABASE_URL="$scratch_dsn" go run ./cmd/chronicle migrate up >/dev/null

# PRIVILEGES are kept deliberately: the tier grants are the doctrine's
# enforcement mechanism, so loosening one must show up here as a schema diff.
#
# OWNERSHIP is not (--no-owner). Who owns an object depends on which role ran
# the migration, which is a deploy concern that provision-db.sh settles — not a
# property of the migrations. Leaving it in makes the artefact differ between a
# CI database and a real one for no useful reason.
#
# Two things are filtered, both non-deterministic rather than meaningful:
#   -- Dumped ...        the server/pg_dump patch version banner
#   \restrict / \unrestrict   a RANDOM nonce pg_dump emits on every run; left
#                        in, the file would differ from itself every time.
{
  echo "-- Generated by scripts/gen-schema.sh from migrations/. Do not edit."
  echo "-- Regenerate with: scripts/gen-schema.sh"
  echo
  pg pg_dump --schema-only --no-owner --no-sync "$scratch_dsn" \
    | grep -vE '^-- Dumped|^\\restrict |^\\unrestrict '
} > "$OUT"

pg psql "$SCHEMAGEN_SUPERUSER_DSN" -v ON_ERROR_STOP=1 -q -c "DROP DATABASE IF EXISTS ${SCRATCH};"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
