// Package wire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package wire

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for JobStatus.
const (
	JobStatusCancelled  JobStatus = "cancelled"
	JobStatusCancelling JobStatus = "cancelling"
	JobStatusFailed     JobStatus = "failed"
	JobStatusLeased     JobStatus = "leased"
	JobStatusQueued     JobStatus = "queued"
	JobStatusRunning    JobStatus = "running"
	JobStatusSucceeded  JobStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusCancelled:
		return true
	case JobStatusCancelling:
		return true
	case JobStatusFailed:
		return true
	case JobStatusLeased:
		return true
	case JobStatusQueued:
		return true
	case JobStatusRunning:
		return true
	case JobStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatus.
const (
	Ready   ReadinessStatus = "ready"
	Unready ReadinessStatus = "unready"
)

// Valid indicates whether the value is a known member of the ReadinessStatus enum.
func (e ReadinessStatus) Valid() bool {
	switch e {
	case Ready:
		return true
	case Unready:
		return true
	default:
		return false
	}
}

// Defines values for ResultStatus.
const (
	ResultStatusCancelled ResultStatus = "cancelled"
	ResultStatusFailed    ResultStatus = "failed"
	ResultStatusSucceeded ResultStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the ResultStatus enum.
func (e ResultStatus) Valid() bool {
	switch e {
	case ResultStatusCancelled:
		return true
	case ResultStatusFailed:
		return true
	case ResultStatusSucceeded:
		return true
	default:
		return false
	}
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	// AcceptedMediaTypes Example: ["audio/ogg","audio/webm","audio/mpeg","audio/mp4","audio/wav"]
	AcceptedMediaTypes []string `json:"accepted_media_types"`

	// DefaultModel Example: small.en
	DefaultModel string `json:"default_model"`

	// Models models this deployment has on disk and will run
	Models []string `json:"models"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Failure defines model for Failure.
type Failure struct {
	// Code Example: decode_failed
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Commit *string `json:"commit,omitempty"`

	// Status Example: ok
	Status  string  `json:"status"`
	Version *string `json:"version,omitempty"`
}

// Job defines model for Job.
type Job struct {
	// Attempts how many times this job has been claimed. Incremented by the reaper
	// when a lease expires. The CEILING and the backoff are CHRN-28's
	// policy; the counter lives here because the reaper moves it.
	Attempts  int                `json:"attempts"`
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Model     string             `json:"model"`

	// RetryAfterMs how long the client should wait before polling again. Absent on a
	// terminal job. Server-set, so a deep queue can back clients off
	// without a contract change.
	RetryAfterMs *int `json:"retry_after_ms,omitempty"`

	// Status Five stored states plus one derived. `leased` is separate from `running`
	// because they answer different questions: a worker has claimed the job,
	// versus inference has actually started — and a worker that dies between
	// the two needs different `attempts` accounting from one that died
	// mid-inference.
	//
	// `cancelling` is DERIVED — a `running` job whose cancellation has been
	// requested. It is in this enum despite not being a stored state because
	// it is observable by two codebases, and a status a client can see but
	// cannot find in the schema is a status one of them will fail to handle.
	Status    JobStatus `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
}

// JobSpec defines model for JobSpec.
type JobSpec struct {
	// AudioSha256 SHA-256 of the audio part, lowercase hex. Carried in the spec so the
	// idempotency mismatch check does not depend on having buffered the
	// body. A client that lies about it gets a job that transcribes bytes
	// the contract believes are something else — a client bug this service
	// cannot and should not defend against.
	AudioSha256 string `json:"audio_sha256"`

	// Language BCP-47 hint; omitted lets the model decide.
	Language *string `json:"language,omitempty"`

	// Model omitted takes the deployment default. A model this deployment does
	// not have is 400 rather than a job that fails later.
	Model *string `json:"model,omitempty"`
}

// JobStatus Five stored states plus one derived. `leased` is separate from `running`
// because they answer different questions: a worker has claimed the job,
// versus inference has actually started — and a worker that dies between
// the two needs different `attempts` accounting from one that died
// mid-inference.
//
// `cancelling` is DERIVED — a `running` job whose cancellation has been
// requested. It is in this enum despite not being a stored state because
// it is observable by two codebases, and a status a client can see but
// cannot find in the schema is a status one of them will fail to handle.
type JobStatus string

// Readiness defines model for Readiness.
type Readiness struct {
	// Check which dependency failed, when unready. `database`, `whisper_server`
	// when the resident process is absent or holds no model, or `standby`
	// when another process holds the device lock — a standby serves the
	// API correctly and cannot transcribe, and naming it keeps a second
	// asrd during a redeploy from reading as a broken one.
	Check *string `json:"check,omitempty"`

	// InferenceRunningMs how long the current inference has been running; absent when the
	// device is idle. Evidence for an operator, NOT a bound — the bound is
	// the per-job deadline the worker applies.
	InferenceRunningMs *int64 `json:"inference_running_ms,omitempty"`

	// QueueDepth jobs not yet in a terminal state
	QueueDepth *int64 `json:"queue_depth,omitempty"`

	// ResidentModel the model the resident worker is holding. Absent when nothing is
	// loaded, which is itself a reason this endpoint answers unready: a
	// service whose GPU has gone but whose database is fine would
	// otherwise report ready and accept work forever.
	ResidentModel *string         `json:"resident_model,omitempty"`
	Status        ReadinessStatus `json:"status"`
}

// ReadinessStatus defines model for Readiness.Status.
type ReadinessStatus string

// Result defines model for Result.
type Result struct {
	// AudioDurationMs as decoded
	AudioDurationMs *int64 `json:"audio_duration_ms,omitempty"`

	// Backend with `model`, stored alongside the transcript by the client — a
	// corpus transcribed by two different models over time is one whose
	// quality varies invisibly.
	//
	//
	// Example: vulkan
	Backend string `json:"backend"`

	// CoveredMs end of the last segment. EVIDENCE, NOT A PREDICATE. Useful when a
	// transcript looks short; never the gate. See `partial`.
	CoveredMs *int64             `json:"covered_ms,omitempty"`
	Failure   *Failure           `json:"failure,omitempty"`
	JobId     openapi_types.UUID `json:"job_id"`

	// Model Example: whisper.cpp/small.en
	Model string `json:"model"`

	// Partial A FACT THE SERVICE RECORDS about whether its own run completed. It
	// is never inferred by a client from `covered_ms < audio_duration_ms`
	// — whisper emits segments only where there is speech, so a memo with
	// five seconds of trailing silence has `covered_ms` short of the
	// duration on a perfectly complete run.
	//
	// A transcript is DURABLE iff its job reached `succeeded` and `partial`
	// is false. That predicate is what CHRN-22's retention pruner gates
	// audio deletion on, read from Chronicle's own transcript row rather
	// than from here.
	Partial  bool         `json:"partial"`
	Segments []Segment    `json:"segments"`
	Status   ResultStatus `json:"status"`

	// Text the transcript, timestamps stripped. EMPTY IS A VALID RESULT: a memo
	// that is forty seconds of silence has a true and complete answer, and
	// the answer is "no speech".
	Text string `json:"text"`
}

// ResultStatus defines model for Result.Status.
type ResultStatus string

// Segment defines model for Segment.
type Segment struct {
	EndMs   int64  `json:"end_ms"`
	StartMs int64  `json:"start_ms"`
	Text    string `json:"text"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// JobID defines model for JobID.
type JobID = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// SubmitJobMultipartBody defines parameters for SubmitJob.
type SubmitJobMultipartBody struct {
	// Audio The recording, in one of the accepted media types. The part
	// declares its own `Content-Type`; anything outside the
	// advertised set is 415.
	Audio openapi_types.File `json:"audio"`
	Spec  JobSpec            `json:"spec"`
}

// SubmitJobParams defines parameters for SubmitJob.
type SubmitJobParams struct {
	// IdempotencyKey Minted per transcription attempt and persisted before the request is
	// sent. Stable across HTTP retries of one attempt; fresh for a deliberate
	// re-transcription. Same name and same meaning as Chronicle's own ingest
	// key (CHRN-18) — one header, one meaning, across the estate.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// SubmitJobMultipartRequestBody defines body for SubmitJob for multipart/form-data ContentType.
type SubmitJobMultipartRequestBody SubmitJobMultipartBody
